P2 Data Scientist, OpenClassrooms

Oumeima EL GHARBI, novembre 2021

Notebook 1 : nettoyage des données.

**Problématique** : Quels sont les pays avec un fort potentiel de clients pour nos services ?
Pour chacun de ces pays, quelle sera l’évolution de ce potentiel de clients ?
Dans quels pays l'entreprise doit-elle opérer en priorité ?

*Question : Quelles sont les variables permettant de quantifier le potentiel d'un pays en vue d'un développement commercial ?*


**Objectif : proposer une liste de pays correspondants aux critères de l'entreprise.**


**Etape 1 : Nettoyage de données dans ce notebook 1**

1) Trouver les définitions des variables et les quatres variables :
- richesse pays
- taille pays
- internet
- taux de présence dans l'enseignment supérieur


2) Analyser la qualité des données : analyser le taux de remplissage par pays et en retirer certains.


**Etape 2 : Analyse de données à l'aide du notebook 2**

Bonus : score d'attractivité par pays

Consignes :
- Valider la qualité de ce jeu de données (comporte-t-il beaucoup de données manquantes, dupliquées ?)

- Décrire les informations contenues dans le jeu de données (nombre de colonnes ? nombre de lignes ?)

- Sélectionner les informations qui semblent pertinentes pour répondre à la problématique (quelles sont les colonnes contenant des informations qui peuvent être utiles pour répondre à la problématique de l’entreprise ?)

- Déterminer des ordres de grandeurs des indicateurs statistiques classiques pour les différentes zones géographiques et pays du monde (moyenne/médiane/écart-type par pays et par continent ou bloc géographique)

In [1057]:
import pandas as pd # traiter les données sous forme de dataframe

# Etape 1 : importer les données via pandas

In [1058]:
df1 = pd.read_csv('csv/EdStatsCountry.csv')
df2 = pd.read_csv('csv/EdStatsCountry_Series.csv')
df3 = pd.read_csv('csv/EdStatsData.csv')
df4 = pd.read_csv('csv/EdStatsFootNote.csv')
df5 = pd.read_csv('csv/EdStatsSeries.csv')

# pour avoir un affichage complet des dataframes
pd.set_option('display.max_columns', None)
pd.set_option('max_columns', None)
pd.set_option('max_colwidth', None)

## A) DataFrame 1 : Country

In [1059]:
# On affiche les 5 premières lignes
display(df1.head())

Country Code   Short Name   Table Name                     Long Name  \
0          ABW        Aruba        Aruba                         Aruba   
1          AFG  Afghanistan  Afghanistan  Islamic State of Afghanistan   
2          AGO       Angola       Angola   People's Republic of Angola   
3          ALB      Albania      Albania           Republic of Albania   
4          AND      Andorra      Andorra       Principality of Andorra   

  2-alpha code   Currency Unit  \
0           AW   Aruban florin   
1           AF  Afghan afghani   
2           AO  Angolan kwanza   
3           AL    Albanian lek   
4           AD            Euro   

                                                                                                                                                                                                                                       Special Notes  \
0                                                                                                      SNA data for 2000-2011 are updated from official government statistics; 1994-1999 from UN databases. Base year has changed from 1995 to 2000.   
1  Fiscal year end: March 20; reporting period for national accounts data: FY (from 2013 are CY). National accounts data are sourced from the IMF and differ from the Central Statistics Organization numbers due to exclusion of the opium economy.   
2                                                                                                                 April 2013 database update: Based on IMF data, national accounts data were revised for 2000 onward; the base year changed to 2002.   
3                                                                                                                                                                                                                                                NaN   
4                                                                                                                                                                                                                                                NaN   

                      Region          Income Group WB-2 code  \
0  Latin America & Caribbean  High income: nonOECD        AW   
1                 South Asia            Low income        AF   
2         Sub-Saharan Africa   Upper middle income        AO   
3      Europe & Central Asia   Upper middle income        AL   
4      Europe & Central Asia  High income: nonOECD        AD   

                          National accounts base year  \
0                                                2000   
1                                             2002/03   
2                                                2002   
3  Original chained constant price data are rescaled.   
4                                                1990   

   National accounts reference year                   SNA price valuation  \
0                               NaN     Value added at basic prices (VAB)   
1                               NaN     Value added at basic prices (VAB)   
2                               NaN  Value added at producer prices (VAP)   
3                            1996.0     Value added at basic prices (VAB)   
4                               NaN                                   NaN   

  Lending category Other groups  \
0              NaN          NaN   
1              IDA         HIPC   
2             IBRD          NaN   
3             IBRD          NaN   
4              NaN          NaN   

                                      System of National Accounts  \
0  Country uses the 1993 System of National Accounts methodology.   
1  Country uses the 1993 System of National Accounts methodology.   
2  Country uses the 1993 System of National Accounts methodology.   
3  Country uses the 1993 System of National Accounts methodology.   
4  Country uses the 1968 System of National Accounts methodology.   

  Alternative conversion factor PPP survey yea

In [1060]:
columns_df1 = df1.columns
display(columns_df1)
    
# On voit que certaines colonnes ne sont pas pertinentes pour notre problématique : on les enlève

Index(['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Alternative conversion factor',
       'PPP survey year', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data'],
      dtype='object')

In [1061]:
# On peut retirer les colonnes suivantes :  

columns_to_drop_df1 = ['Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Special Notes','Region', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Alternative conversion factor',
       'PPP survey year', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data']

# fonction drop permet de retirer les colonnes (visualisation), inplace=True ou bien créer une copie
df1_tri1 = df1.drop(columns = columns_to_drop_df1) 
df1_tri1 = df1_tri1.rename(columns={"Short Name": "Pays"})
display(df1_tri1.head(10))

# intéressant : Income Group 

Country Code                  Pays          Income Group
0          ABW                 Aruba  High income: nonOECD
1          AFG           Afghanistan            Low income
2          AGO                Angola   Upper middle income
3          ALB               Albania   Upper middle income
4          AND               Andorra  High income: nonOECD
5          ARB            Arab World                   NaN
6          ARE  United Arab Emirates  High income: nonOECD
7          ARG             Argentina   Upper middle income
8          ARM               Armenia   Lower middle income
9          ASM        American Samoa   Upper middle income

In [1062]:
print(df1_tri1["Income Group"].unique(), end="\n\n") # On affiche toutes les valeurs possibles de la colonne "Income Group"

df1_tri1.info() # On regarde le taux de remplissage de chaque colonne

['High income: nonOECD' 'Low income' 'Upper middle income' nan
 'Lower middle income' 'High income: OECD']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Country Code  241 non-null    object
 1   Pays          241 non-null    object
 2   Income Group  214 non-null    object
dtypes: object(3)
memory usage: 5.8+ KB


In [1063]:
# on constate que le taux de remplissage pour le revenu est de 89% (214 / 241).
# On gardera tout de même pour l'instant les pays avec des NaN : on va les contrôler un à un.

rows_to_keep_df1 = ['High income: OECD', 'High income: nonOECD']

In [1064]:
display(df1_tri1[df1_tri1['Income Group'].isna()])
# On a ici des régions du monde, ou des zones géographiques : on ne gardera pas ces 27 lignes dont l'income group est NaN.

Country Code                                            Pays Income Group
5            ARB                                      Arab World          NaN
57           EAP           East Asia & Pacific (developing only)          NaN
58           EAS         East Asia & Pacific (all income levels)          NaN
59           ECA         Europe & Central Asia (developing only)          NaN
60           ECS       Europe & Central Asia (all income levels)          NaN
63           EMU                                       Euro area          NaN
68           EUU                                  European Union          NaN
78           GIB                                       Gibraltar          NaN
89           HIC                                     High income          NaN
92           HPC          Heavily indebted poor countries (HIPC)          NaN
116          LAC     Latin America & Caribbean (developing only)          NaN
122          LCN   Latin America & Caribbean (all income levels)          NaN
123          LDC    Least developed countries: UN classification          NaN
124          LIC                                      Low income          NaN
127          LMC                             Lower middle income          NaN
128          LMY                             Low & middle income          NaN
140          MEA  Middle East & North Africa (all income levels)          NaN
143          MIC                                   Middle income          NaN
148          MNA    Middle East & North Africa (developing only)          NaN
157          NAC                                   North America          NaN
166          NRU                                           Nauru          NaN
168          OED                                    OECD members          NaN
187          SAS                                      South Asia          NaN
198          SSA            Sub-Saharan Africa (developing only)          NaN
200          SSF          Sub-Saharan Africa (all income levels)          NaN
225          UMC                             Upper middle income          NaN
234          WLD                                           World          NaN

In [1065]:
df1_tri2 = df1_tri1.copy() # on copie le DF1

# On ne garde que les lignes pour lesquelles les pays ont de hauts revenus
df1_tri2 = df1_tri2[df1_tri2['Income Group'].isin(rows_to_keep_df1)] # on retire tout sauf les High Income
display(df1_tri2)

# Enregistrement au format CSV
df1_tri2.to_csv("csv/richesse.csv", index=False) 

Country Code                      Pays          Income Group
0            ABW                     Aruba  High income: nonOECD
4            AND                   Andorra  High income: nonOECD
6            ARE      United Arab Emirates  High income: nonOECD
10           ATG       Antigua and Barbuda  High income: nonOECD
11           AUS                 Australia     High income: OECD
..           ...                       ...                   ...
210          TCA  Turks and Caicos Islands  High income: nonOECD
218          TTO       Trinidad and Tobago  High income: nonOECD
226          URY                   Uruguay  High income: nonOECD
227          USA             United States     High income: OECD
231          VIR            Virgin Islands  High income: nonOECD

[75 rows x 3 columns]

**Conclusion** : on gardera le dataframe 1 "country" avec le nom du pays et le revenu de la population. Cela nous a permis de ne garder que 75 pays ayant de hauts revenus sur les 241 pays listés. 

## B) DataFrame 2 : Country Series

In [1066]:
display(df2.head())
display(df2.columns)
# DataFrame pas utile pour notre problématique, description CountryCode

CountryCode         SeriesCode  \
0         ABW        SP.POP.TOTL   
1         ABW        SP.POP.GROW   
2         AFG        SP.POP.GROW   
3         AFG  NY.GDP.PCAP.PP.CD   
4         AFG        SP.POP.TOTL   

                                                DESCRIPTION  Unnamed: 3  
0  Data sources : United Nations World Population Prospects         NaN  
1   Data sources: United Nations World Population Prospects         NaN  
2   Data sources: United Nations World Population Prospects         NaN  
3                        Estimates are based on regression.         NaN  
4  Data sources : United Nations World Population Prospects         NaN

Index(['CountryCode', 'SeriesCode', 'DESCRIPTION', 'Unnamed: 3'], dtype='object')

**Conclusion** : on ne gardera pas le dataframe 2 "country series".

## C) DataFrame 3 : Data

In [1067]:
display(df3.head())
display(df3.columns)
df3.info()

Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                                            Indicator Name  \
0             Adjusted net enrolment rate, lower secondary, both sexes (%)   
1                 Adjusted net enrolment rate, lower secondary, female (%)   
2  Adjusted net enrolment rate, lower secondary, gender parity index (GPI)   
3                   Adjusted net enrolment rate, lower secondary, male (%)   
4                     Adjusted net enrolment rate, primary, both sexes (%)   

   Indicator Code       1970       1971       1972       1973       1974  \
0      UIS.NERA.2        NaN        NaN        NaN        NaN        NaN   
1    UIS.NERA.2.F        NaN        NaN        NaN        NaN        NaN   
2  UIS.NERA.2.GPI        NaN        NaN        NaN        NaN        NaN   
3    UIS.NERA.2.M        NaN        NaN        NaN        NaN        NaN   
4     SE.PRM.TENR  54.822121  54.894138  56.209438  57.267109  57.991138   

       1975       1976      1977      1978       1979       1980       1981  \
0       NaN        NaN       NaN       NaN        NaN        NaN        NaN   
1       NaN        NaN       NaN       NaN        NaN        NaN        NaN   
2       NaN        NaN       NaN       NaN        NaN        NaN        NaN   
3       NaN        NaN       NaN       NaN        NaN        NaN        NaN   
4  59.36554  60.999962  61.92268  62.69342  64.383186  65.617767  66.085152   

        1982       1983       1984       1985       1986      1987       1988  \
0        NaN        NaN        NaN        NaN        NaN       NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN       NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN       NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN       NaN        NaN   
4  66.608139  67.290451  68.510094  69.033211  69.944908  71.04187  71.693779   

        1989       1990       1991       1992       1993       1994      1995  \
0        NaN        NaN        NaN        NaN        NaN        NaN       NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN       NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN       NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN       NaN   
4  71.699097  71.995819  72.602837  70.032722  70.464821  72.645683  71.81176   

        1996       1997       1998       1999       2000       2001  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4  73.903511  74.425201  75.110817  76.254318  77.245682  78.800522   

        2002       2003       2004       2005       2006       2007  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4  80.051399  80.805389  81.607063  82.489487  82.685509  83.280342   

        2008       2009       2010      2011       2012      2013       2014  \
0        NaN        NaN        NaN       NaN        NaN       NaN        NaN   
1        NaN        NaN        NaN       NaN        NaN       NaN        NaN   
2        NaN        NaN        NaN       NaN        NaN       NaN        NaN   
3        NaN        NaN        NaN       NaN        NaN       NaN        NaN   
4  84.011871  84.195961  85.211998  85.24514  86.101669  85.51194  85.320152   

   2015  2016  2017  2020  2025  2030  2035  2040  2045  2050  2055  2060  \
0   NaN   NaN   NaN   NaN   

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2020', '2025', '2030', '2035', '2040', '2045',
       '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090',
       '2095', '2100', 'Unnamed: 69'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 886930 entries, 0 to 886929
Data columns (total 70 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Country Name    886930 non-null  object 
 1   Country Code    886930 non-null  object 
 2   Indicator Name  886930 non-null  object 
 3   Indicator Code  886930 non-null  object 
 4   1970            72288 non-null   float64
 5   1971            35537 non-null   float64
 6   1972            35619 non-null   float64
 7   1973            35545 non-null   float64
 8   1974            35730 non-null   float64
 9   1975            87306 non-null   float64
 10  1976            37483 non-null   float64
 11  1977            37574 non-null   float64
 12  1978            37576 non-null   float64
 13  1979            36809 non-null   float64
 14  1980            89122 non-null   float64
 15  1981            38777 non-null   float64
 16  1982            37511 non-null   float64
 17  1983      

On peut retirer les colonnes "Indicator Code" et toutes les colonnes entre 1970 à 2010 où il n'y avait pas d'internet et les colonnes après 2035 où les prédictions sont trop éloignées dans le temps.
On va garder la colonne "Country Code" pour filtrer les pays qui n'ont pas de hauts revenus.

In [1068]:
columns_to_drop_df3 = ['Indicator Code',
       '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978',
       '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2017','2035', '2040', '2045',
       '2050', '2055', '2060', '2065', '2070', '2075', '2080', '2085', '2090',
       '2095', '2100', 'Unnamed: 69']

# on retire 2017 car il y a seulement 143 lignes sur 886930 lignes non nulles, et avec df3_tri2.info() on constate que toute la colonne 2017 est nulle
df3_tri1 = df3.drop(columns = columns_to_drop_df3) 
display(df3_tri1.head())

Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                                            Indicator Name  \
0             Adjusted net enrolment rate, lower secondary, both sexes (%)   
1                 Adjusted net enrolment rate, lower secondary, female (%)   
2  Adjusted net enrolment rate, lower secondary, gender parity index (GPI)   
3                   Adjusted net enrolment rate, lower secondary, male (%)   
4                     Adjusted net enrolment rate, primary, both sexes (%)   

        2010      2011       2012      2013       2014  2015  2016  2020  \
0        NaN       NaN        NaN       NaN        NaN   NaN   NaN   NaN   
1        NaN       NaN        NaN       NaN        NaN   NaN   NaN   NaN   
2        NaN       NaN        NaN       NaN        NaN   NaN   NaN   NaN   
3        NaN       NaN        NaN       NaN        NaN   NaN   NaN   NaN   
4  85.211998  85.24514  86.101669  85.51194  85.320152   NaN   NaN   NaN   

   2025  2030  
0   NaN   NaN  
1   NaN   NaN  
2   NaN   NaN  
3   NaN   NaN  
4   NaN   NaN

In [1069]:
# A présent, nous retirons pays qui ne sont pas référencés dans le dataframe "richesse" issu du dataframe 1.

# PREMIER FILTRE : on ne garde que les 75 pays avec des hauts revenus
# On récupère les "clés" des 75 pays à hauts revenus pour faire le tri dans le df3.
df_country = pd.read_csv('csv/richesse.csv')
list_country_code = df_country["Country Code"].tolist()
#print(list_country_code)

In [1070]:
df3_tri2 = df3_tri1.copy().reset_index(drop=True)
# on ne garde que les pays dont le "country code" est dans le df country
df3_tri2 = df3_tri2[df3_tri2['Country Code'].isin(list_country_code)] 
display(df3_tri2)

Country Name Country Code  \
106285                Andorra          AND   
106286                Andorra          AND   
106287                Andorra          AND   
106288                Andorra          AND   
106289                Andorra          AND   
...                       ...          ...   
872265  Virgin Islands (U.S.)          VIR   
872266  Virgin Islands (U.S.)          VIR   
872267  Virgin Islands (U.S.)          VIR   
872268  Virgin Islands (U.S.)          VIR   
872269  Virgin Islands (U.S.)          VIR   

                                                                 Indicator Name  \
106285             Adjusted net enrolment rate, lower secondary, both sexes (%)   
106286                 Adjusted net enrolment rate, lower secondary, female (%)   
106287  Adjusted net enrolment rate, lower secondary, gender parity index (GPI)   
106288                   Adjusted net enrolment rate, lower secondary, male (%)   
106289                     Adjusted net enrolment rate, primary, both sexes (%)   
...                                                                         ...   
872265                  Youth illiterate population, 15-24 years, male (number)   
872266              Youth literacy rate, population 15-24 years, both sexes (%)   
872267                  Youth literacy rate, population 15-24 years, female (%)   
872268   Youth literacy rate, population 15-24 years, gender parity index (GPI)   
872269                    Youth literacy rate, population 15-24 years, male (%)   

        2010  2011  2012  2013  2014  2015  2016  2020  2025  2030  
106285   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
106286   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
106287   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
106288   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
106289   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
872265   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
872266   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
872267   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
872268   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
872269   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[274875 rows x 13 columns]

On a maintenant 274875 lignes au lieu de 886930 lignes.

In [1071]:
df3_tri2.info()

# Enregistrement au format CSV
df3_tri2.to_csv('csv/indicators.csv', index=False) # index=False pour pas avoir l'index

<class 'pandas.core.frame.DataFrame'>
Int64Index: 274875 entries, 106285 to 872269
Data columns (total 13 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   Country Name    274875 non-null  object 
 1   Country Code    274875 non-null  object 
 2   Indicator Name  274875 non-null  object 
 3   2010            76216 non-null   float64
 4   2011            46201 non-null   float64
 5   2012            47556 non-null   float64
 6   2013            41174 non-null   float64
 7   2014            34024 non-null   float64
 8   2015            43447 non-null   float64
 9   2016            4722 non-null    float64
 10  2020            16324 non-null   float64
 11  2025            16324 non-null   float64
 12  2030            16324 non-null   float64
dtypes: float64(10), object(3)
memory usage: 29.4+ MB


**Conclusion** : Nous avons appliqué un premier filtre au df3 en retirant les colonnes des années avant 2010 et après 2035 et 2017 qui est vide.

Deuxième filtre : nous avons utilisé le df1 filtré pour ne garder que les country code avec de hauts revenus.
Il restait avec le df1 75 pays avec de hauts revenus.

## D) DataFrame 4 : Footnote

In [1072]:
display(df4.head())
display(df4.columns)
# pas utile pour répondre à notre problématique
# print(df4['DESCRIPTION'])

CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.         NaN

Index(['CountryCode', 'SeriesCode', 'Year', 'DESCRIPTION', 'Unnamed: 4'], dtype='object')

**Conclusion** : On ne garde pas le dataframe 4 car il ne contient pas de données permettant de répondre à notre problématique.

## E) DataFrame E : Series

In [1073]:
display(df5.head())
df5.info()

Series Code       Topic  \
0  BAR.NOED.1519.FE.ZS  Attainment   
1     BAR.NOED.1519.ZS  Attainment   
2  BAR.NOED.15UP.FE.ZS  Attainment   
3     BAR.NOED.15UP.ZS  Attainment   
4  BAR.NOED.2024.FE.ZS  Attainment   

                                                           Indicator Name  \
0  Barro-Lee: Percentage of female population age 15-19 with no education   
1         Barro-Lee: Percentage of population age 15-19 with no education   
2    Barro-Lee: Percentage of female population age 15+ with no education   
3           Barro-Lee: Percentage of population age 15+ with no education   
4  Barro-Lee: Percentage of female population age 20-24 with no education   

                                              Short definition  \
0  Percentage of female population age 15-19 with no education   
1         Percentage of population age 15-19 with no education   
2    Percentage of female population age 15+ with no education   
3           Percentage of population age 15+ with no education   
4  Percentage of female population age 20-24 with no education   

                                               Long definition  \
0  Percentage of female population age 15-19 with no education   
1         Percentage of population age 15-19 with no education   
2    Percentage of female population age 15+ with no education   
3           Percentage of population age 15+ with no education   
4  Percentage of female population age 20-24 with no education   

   Unit of measure Periodicity Base Period Other notes Aggregation method  \
0              NaN         NaN         NaN         NaN                NaN   
1              NaN         NaN         NaN         NaN                NaN   
2              NaN         NaN         NaN         NaN                NaN   
3              NaN         NaN         NaN         NaN                NaN   
4              NaN         NaN         NaN         NaN                NaN   

  Limitations and exceptions  Notes from original source General comments  \
0                        NaN                         NaN              NaN   
1                        NaN                         NaN              NaN   
2                        NaN                         NaN              NaN   
3                        NaN                         NaN              NaN   
4                        NaN                         NaN              NaN   

                                                       Source  \
0  Robert J. Barro and Jong-Wha Lee: http://www.barrolee.com/   
1  Robert J. Barro and Jong-Wha Lee: http://www.barrolee.com/   
2  Robert J. Barro and Jong-Wha Lee: http://www.barrolee.com/   
3  Robert J. Barro and Jong-Wha Lee: http://www.barrolee.com/   
4  Robert J. Barro and Jong-Wha Lee: http://www.barrolee.com/   

  Statistical concept and methodology Development relevance  \
0                                 NaN                   NaN   
1                                 NaN                   NaN   
2                                 NaN                   NaN   
3                                 NaN                   NaN   
4                                 NaN                   NaN   

  Related source links  Other web links  Related indicators  License Type  \
0                  NaN              NaN                 NaN           NaN   
1                  NaN              NaN                 NaN           NaN   
2                  NaN              NaN                 NaN           NaN   
3                  NaN              NaN                 NaN           NaN   
4                  NaN              NaN                 NaN           NaN   

   Unnamed: 20  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype  
---  ------                               --------------  -----  
 0   Series Code                          3665 non-null   object 
 1   Topic                                3665 non-null   object 
 2   Indicator Name                       3665 non-null   object 
 3   Short definition                     2156 non-null   object 
 4   Long definition                      3665 non-null   object 
 5   Unit of measure                      0 non-null      float64
 6   Periodicity                          99 non-null     object 
 7   Base Period                          314 non-null    object 
 8   Other notes                          552 non-null    object 
 9   Aggregation method                   47 non-null     object 
 10  Limitations and exceptions           14 non-null     object 
 11  Notes from original source    

In [1074]:
df5_tri1 = df5[["Indicator Name", "Short definition", "Long definition"]] # On choisit les colonnes avec le nom des indicateurs et leurs définitions.
display(df5_tri1.head())

Indicator Name  \
0  Barro-Lee: Percentage of female population age 15-19 with no education   
1         Barro-Lee: Percentage of population age 15-19 with no education   
2    Barro-Lee: Percentage of female population age 15+ with no education   
3           Barro-Lee: Percentage of population age 15+ with no education   
4  Barro-Lee: Percentage of female population age 20-24 with no education   

                                              Short definition  \
0  Percentage of female population age 15-19 with no education   
1         Percentage of population age 15-19 with no education   
2    Percentage of female population age 15+ with no education   
3           Percentage of population age 15+ with no education   
4  Percentage of female population age 20-24 with no education   

                                               Long definition  
0  Percentage of female population age 15-19 with no education  
1         Percentage of population age 15-19 with no education  
2    Percentage of female population age 15+ with no education  
3           Percentage of population age 15+ with no education  
4  Percentage of female population age 20-24 with no education

**Conclusion** : on ne gardera pas le dataframe 5 car les colonnes de celui-ci ne répondent pas à notre problématique. Mais il va nous servir à choisir nos indicateurs pertinents qui se trouvent dans le dataframe 3 lors de la prochaine étape de tri.

# Etape 2 : deuxième filtre : choix des indicateurs du dataframe 3

Nous avons gardé deux dataframe avec un premier filtre. Nous avons ensuite utilisé le df1 pour filtrer le df3 comportant les indicateurs dont nous allons nous servir pour effectuer notre analyse exploratoire.

In [1075]:
# On lit le df3 trié
df_indicators = pd.read_csv("csv/indicators.csv")
#display(df_country.columns, df_indicators.columns)

Nous allons choisir 30 indicateurs pertinents pour notre analyse exploratoire.
Cela se fera avec un contrôle visuel des 4000 indicateurs du jeu de données 3. Cependant, le code ci-dessous sera mis en commentaire pour la lisibilité du notebook.


In [1076]:
#with np.printoptions(threshold=np.inf): # permet d'afficher la liste (en entier) de toutes les lignes possibles (sans doubons) de la colonne "Indicateur Name"
    #display(df3_tri1["Indicator Name"].unique())

In [1077]:
# Voici la liste des 30 indicateurs gardés après un contrôle visuel un à un des 4000 indicateurs.
list_to_sort = ['Internet users (per 100 people)',

    'Youth literacy rate, population 15-24 years, both sexes (%)',
   'Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary',
       'Barro-Lee: Percentage of population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
       'Gross enrolment ratio, tertiary, both sexes (%)',
'Gross outbound enrolment ratio, all regions, both sexes (%)',
       'PIAAC: Adults by proficiency level in problem solving in technology-rich environments (%). Level 3',
       'Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total',
       'Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. No Education. Total',
       'Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total',
       'Wittgenstein Projection: Percentage of the population age 15+ by highest level of educational attainment. Upper Secondary. Total',
                'Adjusted net enrolment rate, upper secondary, both sexes (%)',
       'Net enrolment rate, upper secondary, both sexes (%)',
       'Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary',
 'Barro-Lee: Percentage of population age 15+ with tertiary schooling. Completed Tertiary',
       'Barro-Lee: Percentage of population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',
'Barro-Lee: Percentage of population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)',       
                'Barro-Lee: Population in thousands, age 15+, total',
       'Barro-Lee: Population in thousands, age 20-24, total',
       'Barro-Lee: Population in thousands, age 25-29, total',
    'Population, ages 15-24, total',
'Population, ages 15-64, total',
       'Enrolment in tertiary education per 100,000 inhabitants, both sexes',
       'Enrolment in tertiary education, all programmes, both sexes (number)',
       'Enrolment in upper secondary education, both sexes (number)',
'Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)',
       'Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)',
       "UIS: Percentage of population age 25+ with a completed bachelor's or equivalent degree (ISCED 6). Total",
       'UIS: Percentage of population age 25+ with a completed short-cycle tertiary degree (ISCED 5). Total',
       'UIS: Percentage of population age 25+ with at least completed upper secondary education (ISCED 3 or higher). Total',
       'Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total',
       'Wittgenstein Projection: Percentage of the population age 25-29 by highest level of educational attainment. Upper Secondary. Total',
               ]
#print(len(list_to_sort))

# pour être sûr de n'avoir qu'une seule fois les indicateurs : transformation en ensemble puis en liste à nouveau
list_to_sort = sorted(list(set(list_to_sort))) 
#print(len(list_to_sort))



Nous n'avons pas conservé les indicateurs où les deux sexes n'étaient pas représentés, ou les indicateurs comme le taux d'illétrisme et le PIB par exemple.

Après un contrôle visuel de tous les indicateurs disponibles dans le jeu de données 3, nous allons regarder la définition de chaque indicateur. Pour cela, nous allons afficher toute la ligne du dataframe 5 (après premier filtre déjà effectué) où chacun des indicateurs sont présents.
Cela nous permettra d'effectuer un second filtre pour ne garder que les indicateurs pertinents pour notre problématique.
Nous nous intéressons notamment à la population, à l'accès à internet, au nombre d'étudiants et à la porportion de la population ayant validé le cycle des études secondaires.



Pour la lisibilité du notebook, le code ci-dessous sera commenté.
On affiche pour chacun des 30 indicateurs selectionnés visuellement leur définition dans le df5. Cette opération ne s'est pas montrée très pertinente.

In [1078]:
# .loc permet de trouver une ligne grâce à la connaissance de la valeur d'une cellule d'une colonne.

#for indicator in list_to_sort:
    #display(df5_tri1.loc[df5_tri1['Indicator Name'] == indicator])
    
#display(df5_tri1.loc[df5_tri1['Indicator Name'] == 'Adjusted net enrolment rate, upper secondary, both sexes (%)'])
#display(df5_tri1.loc[df5_tri1['Indicator Name'] == 'Net enrolment rate, upper secondary, both sexes (%)'])
#display(df5_tri1.loc[df5_tri1['Indicator Name'] == 'Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total'])
#display(df5_tri1.loc[df5_tri1['Indicator Name'] == 'Gross enrolment ratio, tertiary, both sexes (%)'])



# Etape 3 : Filtre en fonction du nombre d'habitants

On trie maintenant en fonction du nombre d'habitant par pays. Nous allons voir que nous avons un seul indicateur sur les 5 indicateurs choisis qui nous permette de faire notre étude. Il manque les données sur le nombre de jeunes de 15 à 30 ans de chaque pays.

On choisit de ne garder que les pays ayant au moins 10 millions d'habitants pour ce premier filtre (nous prenons la France comme référence pour notre étude exploratoire).

In [1079]:
# On choisit donc nos variables à partir des indicateurs du df3 pour lesquels nous avions regardé les définitions dans le df5.
list_population = ['Population, ages 15-64, total', 
                   'Barro-Lee: Population in thousands, age 15+, total',
       'Barro-Lee: Population in thousands, age 20-24, total',
       'Barro-Lee: Population in thousands, age 25-29, total',
    'Population, ages 15-24, total']

In [1080]:
df_tri1 = df_indicators.copy() 
df_tri1 = df_tri1[df_tri1['Indicator Name'].isin(list_population)]
display(df_tri1)

# vérifier que pour chaque "indicateur population" le taux remplissage.

Country Name Country Code  \
480                   Andorra          AND   
484                   Andorra          AND   
488                   Andorra          AND   
2482                  Andorra          AND   
2486                  Andorra          AND   
...                       ...          ...   
271690  Virgin Islands (U.S.)          VIR   
271694  Virgin Islands (U.S.)          VIR   
271698  Virgin Islands (U.S.)          VIR   
273692  Virgin Islands (U.S.)          VIR   
273696  Virgin Islands (U.S.)          VIR   

                                              Indicator Name     2010  \
480       Barro-Lee: Population in thousands, age 15+, total      NaN   
484     Barro-Lee: Population in thousands, age 20-24, total      NaN   
488     Barro-Lee: Population in thousands, age 25-29, total      NaN   
2482                           Population, ages 15-24, total      NaN   
2486                           Population, ages 15-64, total      NaN   
...                                                      ...      ...   
271690    Barro-Lee: Population in thousands, age 15+, total      NaN   
271694  Barro-Lee: Population in thousands, age 20-24, total      NaN   
271698  Barro-Lee: Population in thousands, age 25-29, total      NaN   
273692                         Population, ages 15-24, total      NaN   
273696                         Population, ages 15-64, total  69863.0   

           2011     2012     2013     2014     2015     2016  2020  2025  2030  
480         NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
484         NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
488         NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
2482        NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
2486        NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
...         ...      ...      ...      ...      ...      ...   ...   ...   ...  
271690      NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
271694      NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
271698      NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
273692      NaN      NaN      NaN      NaN      NaN      NaN   NaN   NaN   NaN  
273696  68823.0  67757.0  66653.0  65532.0  64411.0  63541.0   NaN   NaN   NaN  

[375 rows x 13 columns]

In [1081]:
# Nous regardons le taux de remplissage pour chacun des 5 indicateurs de population.
x = df_tri1.copy()
for ind_pop in list_population:
    print(ind_pop)
    y = x[x["Indicator Name"] == ind_pop]
    display(y)
    y.info()
    print('\n\n\n\n')

Population, ages 15-64, total


Country Name Country Code                 Indicator Name  \
2486                  Andorra          AND  Population, ages 15-64, total   
6151      Antigua and Barbuda          ATG  Population, ages 15-64, total   
9816                    Aruba          ABW  Population, ages 15-64, total   
13481               Australia          AUS  Population, ages 15-64, total   
17146                 Austria          AUT  Population, ages 15-64, total   
...                       ...          ...                            ...   
259036   United Arab Emirates          ARE  Population, ages 15-64, total   
262701         United Kingdom          GBR  Population, ages 15-64, total   
266366          United States          USA  Population, ages 15-64, total   
270031                Uruguay          URY  Population, ages 15-64, total   
273696  Virgin Islands (U.S.)          VIR  Population, ages 15-64, total   

               2010         2011         2012         2013         2014  \
2486            NaN          NaN          NaN          NaN          NaN   
6151        63172.0      64292.0      65460.0      66630.0      67755.0   
9816        69987.0      70297.0      70754.0      71292.0      71790.0   
13481    14879463.0   15029738.0   15233953.0   15435139.0   15598904.0   
17146     5644039.0    5657956.0    5677901.0    5703424.0    5736127.0   
...             ...          ...          ...          ...          ...   
259036    7102235.0    7427164.0    7612144.0    7694737.0    7739507.0   
262701   41350322.0   41474839.0   41563441.0   41637474.0   41744392.0   
266366  206816889.0  208094512.0  209318529.0  210354971.0  211378325.0   
270031    2144437.0    2156178.0    2167788.0    2179148.0    2190338.0   
273696      69863.0      68823.0      67757.0      66653.0      65532.0   

               2015         2016  2020  2025  2030  
2486            NaN          NaN   NaN   NaN   NaN  
6151        68805.0      69717.0   NaN   NaN   NaN  
9816        72162.0      72487.0   NaN   NaN   NaN  
13481    15745617.0   15887445.0   NaN   NaN   NaN  
17146     5787638.0    5849908.0   NaN   NaN   NaN  
...             ...          ...   ...   ...   ...  
259036    7798697.0    7881775.0   NaN   NaN   NaN  
262701   41873827.0   42028042.0   NaN   NaN   NaN  
266366  212262832.0  213071223.0   NaN   NaN   NaN  
270031    2201356.0    2211820.0   NaN   NaN   NaN  
273696      64411.0      63541.0   NaN   NaN   NaN  

[75 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 2486 to 273696
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    75 non-null     object 
 1   Country Code    75 non-null     object 
 2   Indicator Name  75 non-null     object 
 3   2010            61 non-null     float64
 4   2011            61 non-null     float64
 5   2012            61 non-null     float64
 6   2013            61 non-null     float64
 7   2014            60 non-null     float64
 8   2015            60 non-null     float64
 9   2016            60 non-null     float64
 10  2020            0 non-null      float64
 11  2025            0 non-null      float64
 12  2030            0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 8.2+ KB





Barro-Lee: Population in thousands, age 15+, total


Country Name Country Code  \
480                   Andorra          AND   
4145      Antigua and Barbuda          ATG   
7810                    Aruba          ABW   
11475               Australia          AUS   
15140                 Austria          AUT   
...                       ...          ...   
257030   United Arab Emirates          ARE   
260695         United Kingdom          GBR   
264360          United States          USA   
268025                Uruguay          URY   
271690  Virgin Islands (U.S.)          VIR   

                                            Indicator Name      2010  2011  \
480     Barro-Lee: Population in thousands, age 15+, total       NaN   NaN   
4145    Barro-Lee: Population in thousands, age 15+, total       NaN   NaN   
7810    Barro-Lee: Population in thousands, age 15+, total       NaN   NaN   
11475   Barro-Lee: Population in thousands, age 15+, total   17323.0   NaN   
15140   Barro-Lee: Population in thousands, age 15+, total    7090.0   NaN   
...                                                    ...       ...   ...   
257030  Barro-Lee: Population in thousands, age 15+, total    3998.0   NaN   
260695  Barro-Lee: Population in thousands, age 15+, total   50276.0   NaN   
264360  Barro-Lee: Population in thousands, age 15+, total  249660.0   NaN   
268025  Barro-Lee: Population in thousands, age 15+, total    2737.0   NaN   
271690  Barro-Lee: Population in thousands, age 15+, total       NaN   NaN   

        2012  2013  2014  2015  2016  2020  2025  2030  
480      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4145     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
7810     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11475    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
15140    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...      ...   ...   ...   ...   ...   ...   ...   ...  
257030   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
260695   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
264360   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
268025   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
271690   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[75 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 480 to 271690
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    75 non-null     object 
 1   Country Code    75 non-null     object 
 2   Indicator Name  75 non-null     object 
 3   2010            49 non-null     float64
 4   2011            0 non-null      float64
 5   2012            0 non-null      float64
 6   2013            0 non-null      float64
 7   2014            0 non-null      float64
 8   2015            0 non-null      float64
 9   2016            0 non-null      float64
 10  2020            0 non-null      float64
 11  2025            0 non-null      float64
 12  2030            0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 8.2+ KB





Barro-Lee: Population in thousands, age 20-24, total


Country Name Country Code  \
484                   Andorra          AND   
4149      Antigua and Barbuda          ATG   
7814                    Aruba          ABW   
11479               Australia          AUS   
15144                 Austria          AUT   
...                       ...          ...   
257034   United Arab Emirates          ARE   
260699         United Kingdom          GBR   
264364          United States          USA   
268029                Uruguay          URY   
271694  Virgin Islands (U.S.)          VIR   

                                              Indicator Name     2010  2011  \
484     Barro-Lee: Population in thousands, age 20-24, total      NaN   NaN   
4149    Barro-Lee: Population in thousands, age 20-24, total      NaN   NaN   
7814    Barro-Lee: Population in thousands, age 20-24, total      NaN   NaN   
11479   Barro-Lee: Population in thousands, age 20-24, total   1478.0   NaN   
15144   Barro-Lee: Population in thousands, age 20-24, total    489.0   NaN   
...                                                      ...      ...   ...   
257034  Barro-Lee: Population in thousands, age 20-24, total    452.0   NaN   
260699  Barro-Lee: Population in thousands, age 20-24, total   4202.0   NaN   
264364  Barro-Lee: Population in thousands, age 20-24, total  22417.0   NaN   
268029  Barro-Lee: Population in thousands, age 20-24, total    262.0   NaN   
271694  Barro-Lee: Population in thousands, age 20-24, total      NaN   NaN   

        2012  2013  2014  2015  2016  2020  2025  2030  
484      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4149     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
7814     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11479    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
15144    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...      ...   ...   ...   ...   ...   ...   ...   ...  
257034   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
260699   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
264364   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
268029   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
271694   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[75 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 484 to 271694
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    75 non-null     object 
 1   Country Code    75 non-null     object 
 2   Indicator Name  75 non-null     object 
 3   2010            49 non-null     float64
 4   2011            0 non-null      float64
 5   2012            0 non-null      float64
 6   2013            0 non-null      float64
 7   2014            0 non-null      float64
 8   2015            0 non-null      float64
 9   2016            0 non-null      float64
 10  2020            0 non-null      float64
 11  2025            0 non-null      float64
 12  2030            0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 8.2+ KB





Barro-Lee: Population in thousands, age 25-29, total


Country Name Country Code  \
488                   Andorra          AND   
4153      Antigua and Barbuda          ATG   
7818                    Aruba          ABW   
11483               Australia          AUS   
15148                 Austria          AUT   
...                       ...          ...   
257038   United Arab Emirates          ARE   
260703         United Kingdom          GBR   
264368          United States          USA   
268033                Uruguay          URY   
271698  Virgin Islands (U.S.)          VIR   

                                              Indicator Name     2010  2011  \
488     Barro-Lee: Population in thousands, age 25-29, total      NaN   NaN   
4153    Barro-Lee: Population in thousands, age 25-29, total      NaN   NaN   
7818    Barro-Lee: Population in thousands, age 25-29, total      NaN   NaN   
11483   Barro-Lee: Population in thousands, age 25-29, total   1500.0   NaN   
15148   Barro-Lee: Population in thousands, age 25-29, total    516.0   NaN   
...                                                      ...      ...   ...   
257038  Barro-Lee: Population in thousands, age 25-29, total    548.0   NaN   
260703  Barro-Lee: Population in thousands, age 25-29, total   3949.0   NaN   
264368  Barro-Lee: Population in thousands, age 25-29, total  21740.0   NaN   
268033  Barro-Lee: Population in thousands, age 25-29, total    250.0   NaN   
271698  Barro-Lee: Population in thousands, age 25-29, total      NaN   NaN   

        2012  2013  2014  2015  2016  2020  2025  2030  
488      NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4153     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
7818     NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11483    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
15148    NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...      ...   ...   ...   ...   ...   ...   ...   ...  
257038   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
260703   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
264368   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
268033   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
271698   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[75 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 488 to 271698
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    75 non-null     object 
 1   Country Code    75 non-null     object 
 2   Indicator Name  75 non-null     object 
 3   2010            49 non-null     float64
 4   2011            0 non-null      float64
 5   2012            0 non-null      float64
 6   2013            0 non-null      float64
 7   2014            0 non-null      float64
 8   2015            0 non-null      float64
 9   2016            0 non-null      float64
 10  2020            0 non-null      float64
 11  2025            0 non-null      float64
 12  2030            0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 8.2+ KB





Population, ages 15-24, total


Country Name Country Code                 Indicator Name  \
2482                  Andorra          AND  Population, ages 15-24, total   
6147      Antigua and Barbuda          ATG  Population, ages 15-24, total   
9812                    Aruba          ABW  Population, ages 15-24, total   
13477               Australia          AUS  Population, ages 15-24, total   
17142                 Austria          AUT  Population, ages 15-24, total   
...                       ...          ...                            ...   
259032   United Arab Emirates          ARE  Population, ages 15-24, total   
262697         United Kingdom          GBR  Population, ages 15-24, total   
266362          United States          USA  Population, ages 15-24, total   
270027                Uruguay          URY  Population, ages 15-24, total   
273692  Virgin Islands (U.S.)          VIR  Population, ages 15-24, total   

              2010        2011        2012        2013        2014  \
2482           NaN         NaN         NaN         NaN         NaN   
6147           NaN         NaN         NaN         NaN         NaN   
9812       13299.0     13466.0     13708.0     13990.0     14253.0   
13477    2914315.0   2922445.0   2926388.0   2926254.0   2922207.0   
17142    1008570.0   1003625.0    996625.0    987677.0    976937.0   
...            ...         ...         ...         ...         ...   
259032    683545.0    692184.0    704899.0    719641.0    733259.0   
262697   8035314.0   8005514.0   7955051.0   7888589.0   7812258.0   
266362  45137089.0  45296141.0  45343097.0  45307415.0  45230846.0   
270027    515960.0    518707.0    520300.0    520793.0    520399.0   
273692         NaN         NaN         NaN         NaN         NaN   

              2015  2016  2020  2025  2030  
2482           NaN   NaN   NaN   NaN   NaN  
6147           NaN   NaN   NaN   NaN   NaN  
9812       14455.0   NaN   NaN   NaN   NaN  
13477    2914620.0   NaN   NaN   NaN   NaN  
17142     964629.0   NaN   NaN   NaN   NaN  
...            ...   ...   ...   ...   ...  
259032    743608.0   NaN   NaN   NaN   NaN  
262697   7731522.0   NaN   NaN   NaN   NaN  
266362  45147517.0   NaN   NaN   NaN   NaN  
270027    519298.0   NaN   NaN   NaN   NaN  
273692         NaN   NaN   NaN   NaN   NaN  

[75 rows x 13 columns]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 2482 to 273692
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    75 non-null     object 
 1   Country Code    75 non-null     object 
 2   Indicator Name  75 non-null     object 
 3   2010            53 non-null     float64
 4   2011            53 non-null     float64
 5   2012            53 non-null     float64
 6   2013            53 non-null     float64
 7   2014            53 non-null     float64
 8   2015            53 non-null     float64
 9   2016            0 non-null      float64
 10  2020            0 non-null      float64
 11  2025            0 non-null      float64
 12  2030            0 non-null      float64
dtypes: float64(10), object(3)
memory usage: 8.2+ KB







Nous constatons que sur les cinq indicateurs de population, celui ayant le meilleur taux de remplissage est 'Population, ages 15-64, total'.

Nous ne gardons donc que cet indicateur et nous allons retirer les pays trop petits pour l'implémentation d'un établissement de formation en ligne. Nous prenons arbitrairement 10 millions d'habitants comme seuil minimum.
Nous utilisetons plus tard l'indicateur du nombre d'étudiants de l'enseignement supérieur pour comparer ces pays (jeunes de 15 à 30 ans).

Nous avons un taux de remplissage de 60/75 % soit de 80%.

Nous gardons la colonne 2016 étant la plus proche de 2020.

In [1082]:
df_population = df_tri1.copy()
df_population = df_population[df_population["Indicator Name"] == 'Population, ages 15-64, total']

df_population.drop(columns = ['2010', '2011', '2012', '2013', '2020', '2025', '2030'], inplace=True)

# Nous avons vérifié que les NaN pour 2016 correspondaient à de petits pays.
x = df_population[df_population["2016"].isna()]
x = x["Country Name"] # Ce sont les 15 pays pour lesquels nous n'avions pas de valeurs.
display(x) # Après un contrôle visuel, nous constatons que ce sont des pays comportant peu d'habitants.

df_population = df_population.dropna(axis='rows') # nous retirons les 15 petits pays.

# tri dans l'ordre décroissant, d'abord 2016 puis 2015 puis 2014
df_population.sort_values(by=['2016', '2015', '2014'], ascending=False, inplace=True) 

display(df_population)
df_population.describe(include = 'all')


2486                        Andorra
35471                       Bermuda
46466                Cayman Islands
61126                       Curacao
83116                 Faroe Islands
105106                    Greenland
123431                  Isle of Man
149086                Liechtenstein
167411                       Monaco
182071     Northern Mariana Islands
211391                   San Marino
222386    Sint Maarten (Dutch part)
237046          St. Kitts and Nevis
240711     St. Martin (French part)
255371     Turks and Caicos Islands
Name: Country Name, dtype: object

Country Name Country Code                 Indicator Name  \
266366          United States          USA  Population, ages 15-64, total   
207726     Russian Federation          RUS  Population, ages 15-64, total   
134426                  Japan          JPN  Population, ages 15-64, total   
97776                 Germany          DEU  Population, ages 15-64, total   
262701         United Kingdom          GBR  Population, ages 15-64, total   
90446                  France          FRA  Population, ages 15-64, total   
130761                  Italy          ITA  Population, ages 15-64, total   
138091            Korea, Rep.          KOR  Population, ages 15-64, total   
233381                  Spain          ESP  Population, ages 15-64, total   
193066                 Poland          POL  Population, ages 15-64, total   
42801                  Canada          CAN  Population, ages 15-64, total   
215056           Saudi Arabia          SAU  Population, ages 15-64, total   
13481               Australia          AUS  Population, ages 15-64, total   
53796                   Chile          CHL  Population, ages 15-64, total   
171076            Netherlands          NLD  Population, ages 15-64, total   
259036   United Arab Emirates          ARE  Population, ages 15-64, total   
31806                 Belgium          BEL  Population, ages 15-64, total   
101441                 Greece          GRC  Population, ages 15-64, total   
68456          Czech Republic          CZE  Population, ages 15-64, total   
196731               Portugal          PRT  Population, ages 15-64, total   
244376                 Sweden          SWE  Population, ages 15-64, total   
17146                 Austria          AUT  Population, ages 15-64, total   
248041            Switzerland          CHE  Population, ages 15-64, total   
112436   Hong Kong SAR, China          HKG  Population, ages 15-64, total   
127096                 Israel          ISR  Population, ages 15-64, total   
218721              Singapore          SGP  Population, ages 15-64, total   
226051        Slovak Republic          SVK  Population, ages 15-64, total   
72121                 Denmark          DNK  Population, ages 15-64, total   
86781                 Finland          FIN  Population, ages 15-64, total   
185736                 Norway          NOR  Population, ages 15-64, total   
189401                   Oman          OMN  Population, ages 15-64, total   
141756                 Kuwait          KWT  Population, ages 15-64, total   
119766                Ireland          IRL  Population, ages 15-64, total   
178406            New Zealand          NZL  Population, ages 15-64, total   
57461                 Croatia          HRV  Population, ages 15-64, total   
200396            Puerto Rico          PRI  Population, ages 15-64, total   
270031                Uruguay          URY  Population, ages 15-64, total   
204061                  Qatar          QAT  Population, ages 15-64, total   
152751              Lithuania          LTU  Population, ages 15-64, total   
229716               Slovenia          SVN  Population, ages 15-64, total   
145421                 Latvia          LVA  Population, ages 15-64, total   
24476                 Bahrain          BHR  Population, ages 15-64, total   
251706    Trinidad and Tobago          TTO  Population, ages 15-64, total   
79451                 Estonia          EST  Population, ages 15-64, total   
64791                  Cyprus          CYP  Population, ages 15-64, total   
75786       Equatorial Guinea          GNQ  Population, ages 15-64, total   
160081       Macao SAR, China          MAC  Population, ages 15-64, total   
156416             Luxembourg          LUX  Population, ages 15-64, total   
39136       Brunei Darussalam          BRN  Population, ages 15-64, total   
163746                  Malta          MLT  Population, ages 15-64, total   
20811            Bahamas, The          BHS  Population, ages 15-64, total   
116101       

Country Name Country Code                 Indicator Name  \
count              60           60                             60   
unique             60           60                              1   
top     United States          USA  Population, ages 15-64, total   
freq                1            1                             60   
mean              NaN          NaN                            NaN   
std               NaN          NaN                            NaN   
min               NaN          NaN                            NaN   
25%               NaN          NaN                            NaN   
50%               NaN          NaN                            NaN   
75%               NaN          NaN                            NaN   
max               NaN          NaN                            NaN   

                2014          2015          2016  
count   6.000000e+01  6.000000e+01  6.000000e+01  
unique           NaN           NaN           NaN  
top              NaN           NaN           NaN  
freq             NaN           NaN           NaN  
mean    1.436265e+07  1.437822e+07  1.439438e+07  
std     3.233751e+07  3.237689e+07  3.240456e+07  
min     6.553200e+04  6.441100e+04  6.354100e+04  
25%     7.764732e+05  7.872628e+05  7.969128e+05  
50%     3.206844e+06  3.291065e+06  3.389333e+06  
75%     8.571770e+06  8.615490e+06  8.678536e+06  
max     2.113783e+08  2.122628e+08  2.130712e+08

Nous allons garder tous les pays ayant au moins 10 millions d'habitants. 

In [1083]:
df_population = df_population[df_population['2016'] > 10000000]
display(df_population)

df_population.drop(columns = ['2014', '2015'], inplace=True) # apres la comparaison on retire les anciennes années
display(df_population)
df_population.to_csv('csv/population.csv', index=False)


Country Name Country Code                 Indicator Name  \
266366       United States          USA  Population, ages 15-64, total   
207726  Russian Federation          RUS  Population, ages 15-64, total   
134426               Japan          JPN  Population, ages 15-64, total   
97776              Germany          DEU  Population, ages 15-64, total   
262701      United Kingdom          GBR  Population, ages 15-64, total   
90446               France          FRA  Population, ages 15-64, total   
130761               Italy          ITA  Population, ages 15-64, total   
138091         Korea, Rep.          KOR  Population, ages 15-64, total   
233381               Spain          ESP  Population, ages 15-64, total   
193066              Poland          POL  Population, ages 15-64, total   
42801               Canada          CAN  Population, ages 15-64, total   
215056        Saudi Arabia          SAU  Population, ages 15-64, total   
13481            Australia          AUS  Population, ages 15-64, total   
53796                Chile          CHL  Population, ages 15-64, total   
171076         Netherlands          NLD  Population, ages 15-64, total   

               2014         2015         2016  
266366  211378325.0  212262832.0  213071223.0  
207726  101035287.0  100404879.0   99477057.0  
134426   78379970.0   77547638.0   76831284.0  
97776    53327698.0   53720119.0   54263836.0  
262701   41744392.0   41873827.0   42028042.0  
90446    41917948.0   41837530.0   41796373.0  
130761   39035661.0   38813169.0   38591970.0  
138091   37193108.0   37307195.0   37364822.0  
233381   30946615.0   30755139.0   30678609.0  
193066   26612967.0   26402284.0   26187409.0  
42801    24258899.0   24332020.0   24477514.0  
215056   21682073.0   22389217.0   23013048.0  
13481    15598904.0   15745617.0   15887445.0  
53796    12107339.0   12210505.0   12304561.0  
171076   11068561.0   11065869.0   11068819.0

Country Name Country Code                 Indicator Name  \
266366       United States          USA  Population, ages 15-64, total   
207726  Russian Federation          RUS  Population, ages 15-64, total   
134426               Japan          JPN  Population, ages 15-64, total   
97776              Germany          DEU  Population, ages 15-64, total   
262701      United Kingdom          GBR  Population, ages 15-64, total   
90446               France          FRA  Population, ages 15-64, total   
130761               Italy          ITA  Population, ages 15-64, total   
138091         Korea, Rep.          KOR  Population, ages 15-64, total   
233381               Spain          ESP  Population, ages 15-64, total   
193066              Poland          POL  Population, ages 15-64, total   
42801               Canada          CAN  Population, ages 15-64, total   
215056        Saudi Arabia          SAU  Population, ages 15-64, total   
13481            Australia          AUS  Population, ages 15-64, total   
53796                Chile          CHL  Population, ages 15-64, total   
171076         Netherlands          NLD  Population, ages 15-64, total   

               2016  
266366  213071223.0  
207726   99477057.0  
134426   76831284.0  
97776    54263836.0  
262701   42028042.0  
90446    41796373.0  
130761   38591970.0  
138091   37364822.0  
233381   30678609.0  
193066   26187409.0  
42801    24477514.0  
215056   23013048.0  
13481    15887445.0  
53796    12304561.0  
171076   11068819.0

Nous avons une liste de pays riches ayant plus de 10 millions d'habitants d'après les données disponibles. Nous avons 6 pays de plus de 40 millions habitants (nous prenons la France comme référence).


In [1084]:
COUNTRIES = df_population['Country Name'].tolist() # liste des pays présentés par ordre décroissant de population
COUNTRY_CODES_last = df_population['Country Code'].tolist() #*
print(COUNTRIES, end="\n\n\n")

#print(COUNTRY_CODES_last)
#print(len(COUNTRY_CODES_last))

['United States', 'Russian Federation', 'Japan', 'Germany', 'United Kingdom', 'France', 'Italy', 'Korea, Rep.', 'Spain', 'Poland', 'Canada', 'Saudi Arabia', 'Australia', 'Chile', 'Netherlands']




In [1085]:
# Nous créons un score d'attractivité : nous notons de 1 à 15 en fonction de l'ordre dans la liste
score = dict()

def add_score(score, countries):
    """
    Function that adds a new score to the dict of attractivity score
    
    :score (dict): the dictionnary containing the scores
    :countries (list): the list of countries ordered
    :return: (dict) The dictionary modified
    
    :CU: we supposed 'score' always contains the same country names
    """
    for i in range(len(countries)):
        if countries[i] in score:
            score[countries[i]] += 15 - i
        else:
            score[countries[i]] = 15 - i
    return score

add_score(score, COUNTRIES)
print(score)
    

{'United States': 15, 'Russian Federation': 14, 'Japan': 13, 'Germany': 12, 'United Kingdom': 11, 'France': 10, 'Italy': 9, 'Korea, Rep.': 8, 'Spain': 7, 'Poland': 6, 'Canada': 5, 'Saudi Arabia': 4, 'Australia': 3, 'Chile': 2, 'Netherlands': 1}


Nous allons utiliser cette liste de pays pour filtrer le df3 avec les indicateurs d'éducation et d'internet.

In [1086]:
# Nous copions notre liste des 30 indicateurs et retirons les 5 indicateurs de population que nous avons déjà étudié.
list_indicators = [ind for ind in list_to_sort if not(ind in list_population)]
#print(len(list_indicators)) # 25 indicateurs

In [1087]:
df_final = pd.read_csv("csv/indicators.csv").copy()

# on ne garde que les country code des 15 pays riches et très peuplés.
df_final = df_final [df_final['Country Code'].isin(COUNTRY_CODES_last)] # *
df_final = df_final[df_final['Indicator Name'].isin(list_indicators)]

# on retire la colonne Country Code après avoir gardé nos 15 pays pré-sélectionnés.
df_final = df_final.drop(columns="Country Code") 
display(df_final)


Country Name  \
11003       Australia   
11372       Australia   
11374       Australia   
11375       Australia   
11396       Australia   
...               ...   
267365  United States   
267368  United States   
267392  United States   
267458  United States   
267541  United States   

                                                                                                                            Indicator Name  \
11003                                                                         Adjusted net enrolment rate, upper secondary, both sexes (%)   
11372                                            Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary   
11374                                              Barro-Lee: Percentage of population age 15+ with tertiary schooling. Completed Tertiary   
11375                       Barro-Lee: Percentage of population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)   
11396                       Barro-Lee: Percentage of population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)   
...                                                                                                                                    ...   
267365       Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. No Education. Total   
267368     Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
267392  Wittgenstein Projection: Percentage of the population age 25-29 by highest level of educational attainment. Upper Secondary. Total   
267458       Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
267541                                                                         Youth literacy rate, population 15-24 years, both sexes (%)   

         2010  2011  2012       2013  2014  2015  2016  2020  2025  2030  
11003     NaN   NaN   NaN  76.045959   NaN   NaN   NaN   NaN   NaN   NaN  
11372   38.49   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11374   18.52   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11375   30.98   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11396   38.00   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...        ...   ...   ...   ...   ...   ...   ...  
267365   0.01   NaN   NaN        NaN   NaN  0.01   NaN  0.01  0.00  0.00  
267368   0.36   NaN   NaN        NaN   NaN  0.38   NaN  0.39  0.41  0.42  
267392   0.52   NaN   NaN        NaN   NaN  0.51   NaN  0.50  0.50  0.49  
267458   0.25   NaN   NaN        NaN   NaN  0.27   NaN  0.28  0.30  0.31  
267541    NaN   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[375 rows x 12 columns]

# Etape 4 : Internet 

On regarde maintenant si on a des NaN dans les 25 indicateurs choisis et on filtre encore une fois.
On commence par l'indicateur des utilisateurs d'internet.

Résumé des étapes : 
- Premier filtre : richesse des pays.
- Deuxième filtre : population de plus de 10 milllions d'habitants.
- Troisième filtre : internet.

Nous verrons plus bas que le taux de remplissage est de 100% pour ces 15 pays riches et de plus de 10 millions d'habitants pour les années de 2010 à 2016.

In [1088]:
df_internet = df_final.copy()
df_internet = df_internet[df_internet["Indicator Name"] == 'Internet users (per 100 people)']
display(df_internet)
df_internet.info()

Country Name                   Indicator Name   2010       2011  \
12370            Australia  Internet users (per 100 people)  76.00  79.487698   
41690               Canada  Internet users (per 100 people)  80.30  83.000000   
52685                Chile  Internet users (per 100 people)  45.00  52.249607   
89335               France  Internet users (per 100 people)  77.28  77.819999   
96665              Germany  Internet users (per 100 people)  82.00  81.270000   
129650               Italy  Internet users (per 100 people)  53.68  54.389998   
133315               Japan  Internet users (per 100 people)  78.21  79.054114   
136980         Korea, Rep.  Internet users (per 100 people)  83.70  83.759120   
169965         Netherlands  Internet users (per 100 people)  90.72  91.419996   
191955              Poland  Internet users (per 100 people)  62.32  61.949999   
206615  Russian Federation  Internet users (per 100 people)  43.00  49.000000   
213945        Saudi Arabia  Internet users (per 100 people)  41.00  47.500000   
232270               Spain  Internet users (per 100 people)  65.80  67.089999   
261590      United Kingdom  Internet users (per 100 people)  85.00  85.379999   
265255       United States  Internet users (per 100 people)  71.69  69.729461   

             2012       2013       2014       2015       2016  2020  2025  \
12370   79.000000  83.453497  84.000000  84.560519  88.238658   NaN   NaN   
41690   83.000000  85.800000  87.120000  88.470000  89.840000   NaN   NaN   
52685   55.050000  58.000000  61.110000  64.289000  66.010000   NaN   NaN   
89335   81.440000  81.919800  83.750000  84.694500  85.622200   NaN   NaN   
96665   82.349998  84.170000  86.190000  87.589800  89.647101   NaN   NaN   
129650  55.829998  58.459300  55.638460  58.141735  61.324253   NaN   NaN   
133315  79.496400  88.219429  89.106833  91.058028  92.000000   NaN   NaN   
136980  84.070000  84.770000  87.556826  89.648631  92.716545   NaN   NaN   
169965  92.859992  93.956400  91.666666  91.724138  90.410959   NaN   NaN   
191955  62.309997  62.849200  66.600000  67.997000  73.300700   NaN   NaN   
206615  63.800000  67.970000  70.520000  73.410000  76.409085   NaN   NaN   
213945  54.000000  60.500000  64.713657  69.616236  73.750904   NaN   NaN   
232270  69.810000  71.635000  76.190000  78.689600  80.561333   NaN   NaN   
261590  87.479998  89.844100  91.610000  92.000300  94.775801   NaN   NaN   
265255  74.700000  71.400000  73.000000  74.554202  76.176737   NaN   NaN   

        2030  
12370    NaN  
41690    NaN  
52685    NaN  
89335    NaN  
96665    NaN  
129650   NaN  
133315   NaN  
136980   NaN  
169965   NaN  
191955   NaN  
206615   NaN  
213945   NaN  
232270   NaN  
261590   NaN  
265255   NaN

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 12370 to 265255
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country Name    15 non-null     object 
 1   Indicator Name  15 non-null     object 
 2   2010            15 non-null     float64
 3   2011            15 non-null     float64
 4   2012            15 non-null     float64
 5   2013            15 non-null     float64
 6   2014            15 non-null     float64
 7   2015            15 non-null     float64
 8   2016            15 non-null     float64
 9   2020            0 non-null      float64
 10  2025            0 non-null      float64
 11  2030            0 non-null      float64
dtypes: float64(10), object(2)
memory usage: 1.5+ KB


In [1089]:
# On retire les années après 2016 car elles ont un taux de remplissage de 0%.
# On retire aussi les années avant 2015 car 2015 et 2016 sont remplies à 100%.

df_internet.drop(columns=['2010', '2011', '2012', '2013', '2014', '2020', '2025', '2030'], inplace=True) 
df_internet.sort_values(by=['2016', '2015'], ascending=False, inplace=True) 

# Après la comparaison on retire les anciennes années
df_internet.drop(columns = '2015', inplace=True) 
display(df_internet)

df_internet.to_csv('csv/internet.csv', index=False)

Country Name                   Indicator Name       2016
261590      United Kingdom  Internet users (per 100 people)  94.775801
136980         Korea, Rep.  Internet users (per 100 people)  92.716545
133315               Japan  Internet users (per 100 people)  92.000000
169965         Netherlands  Internet users (per 100 people)  90.410959
41690               Canada  Internet users (per 100 people)  89.840000
96665              Germany  Internet users (per 100 people)  89.647101
12370            Australia  Internet users (per 100 people)  88.238658
89335               France  Internet users (per 100 people)  85.622200
232270               Spain  Internet users (per 100 people)  80.561333
206615  Russian Federation  Internet users (per 100 people)  76.409085
265255       United States  Internet users (per 100 people)  76.176737
213945        Saudi Arabia  Internet users (per 100 people)  73.750904
191955              Poland  Internet users (per 100 people)  73.300700
52685                Chile  Internet users (per 100 people)  66.010000
129650               Italy  Internet users (per 100 people)  61.324253

In [1090]:
l_internet = df_internet["Country Name"].tolist()
print(l_internet, end="\n\n")
add_score(score, l_internet)
print(score) # Vérification UK : 11 + 15 = 26 ok / Netherlands : 1 + 12 = 13 ok

['United Kingdom', 'Korea, Rep.', 'Japan', 'Netherlands', 'Canada', 'Germany', 'Australia', 'France', 'Spain', 'Russian Federation', 'United States', 'Saudi Arabia', 'Poland', 'Chile', 'Italy']

{'United States': 20, 'Russian Federation': 20, 'Japan': 26, 'Germany': 22, 'United Kingdom': 26, 'France': 18, 'Italy': 10, 'Korea, Rep.': 22, 'Spain': 14, 'Poland': 9, 'Canada': 16, 'Saudi Arabia': 8, 'Australia': 12, 'Chile': 4, 'Netherlands': 13}


# Etape 5 : dernier indicateur : nombre et taux d'étudiants dans le secondaire et le tertiare 

In [1091]:
# Pour la lisibilité du notebook, nous laissons en commentaire le code ci-dessous.

x = df_final.copy()
display(x)
list_attendance = list_indicators.copy()
list_attendance.remove('Internet users (per 100 people)')

#print(len(list_attendance)) # il nous reste 24 indicateurs à étudier

#for ind in list_attendance:
    #print(ind)
    #y = x[x["Indicator Name"] == ind]
    #y.info()
    #print('\n\n\n\n')

Country Name  \
11003       Australia   
11372       Australia   
11374       Australia   
11375       Australia   
11396       Australia   
...               ...   
267365  United States   
267368  United States   
267392  United States   
267458  United States   
267541  United States   

                                                                                                                            Indicator Name  \
11003                                                                         Adjusted net enrolment rate, upper secondary, both sexes (%)   
11372                                            Barro-Lee: Percentage of population age 15+ with secondary schooling. Completed Secondary   
11374                                              Barro-Lee: Percentage of population age 15+ with tertiary schooling. Completed Tertiary   
11375                       Barro-Lee: Percentage of population age 15+ with tertiary schooling. Total (Incomplete and Completed Tertiary)   
11396                       Barro-Lee: Percentage of population age 25+ with tertiary schooling. Total (Incomplete and Completed Tertiary)   
...                                                                                                                                    ...   
267365       Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. No Education. Total   
267368     Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
267392  Wittgenstein Projection: Percentage of the population age 25-29 by highest level of educational attainment. Upper Secondary. Total   
267458       Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
267541                                                                         Youth literacy rate, population 15-24 years, both sexes (%)   

         2010  2011  2012       2013  2014  2015  2016  2020  2025  2030  
11003     NaN   NaN   NaN  76.045959   NaN   NaN   NaN   NaN   NaN   NaN  
11372   38.49   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11374   18.52   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11375   30.98   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
11396   38.00   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...        ...   ...   ...   ...   ...   ...   ...  
267365   0.01   NaN   NaN        NaN   NaN  0.01   NaN  0.01  0.00  0.00  
267368   0.36   NaN   NaN        NaN   NaN  0.38   NaN  0.39  0.41  0.42  
267392   0.52   NaN   NaN        NaN   NaN  0.51   NaN  0.50  0.50  0.49  
267458   0.25   NaN   NaN        NaN   NaN  0.27   NaN  0.28  0.30  0.31  
267541    NaN   NaN   NaN        NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[375 rows x 12 columns]

En fonction des taux de remplissages des 24 indicateurs restants, nous en choisissons 11 !
Nous en faison l'étude au cas par cas plus bas.

**Nous aurons ainsi étudié 13 indicateurs pour 15 pays pré-sélectionnés.**

In [1092]:
# Voici la liste des 11 indicateurs restants à étudier
attendance_ind = ['Adjusted net enrolment rate, upper secondary, both sexes (%)',
                  'Net enrolment rate, upper secondary, both sexes (%)',
'Enrolment in tertiary education per 100,000 inhabitants, both sexes',
'Enrolment in tertiary education, all programmes, both sexes (number)',
'Enrolment in upper secondary education, both sexes (number)',
'Gross enrolment ratio, tertiary, both sexes (%)',
'Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)',
'Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)',


'Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total',
'Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total',
'Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total'
]
#print(len(attendance_ind))

## 1 :  'Adjusted net enrolment rate, upper secondary, both sexes (%)'

In [1093]:
ind_att = attendance_ind[0]
df_1 = df_final.copy()
df_1 = df_1[df_1["Indicator Name"] == ind_att]
#display(df_1)

**Imputation par la méthode par le plus proche voisin** : on attribue à l’enregistrement
pour lequel la réponse à une question manque la valeur figurant pour cette question
dans l’enregistrement obtenu pour le répondant le plus proche, où l’expression « le
plus proche » est habituellement définie par une fonction de distance basée sur une ou
plusieurs variables auxiliaires. 

Cela signifie que l'on va compléter les données manquantes pour l'année étudiée par la donnée de l'année précédente.

**Méthode** : on trie dans l'ordre décroissant en commençant par les colonnes les plus récentes donc 2014 puis 2013.
Nous constatons que nous avons 7 lignes sur 15 remplies pour 2014 : nous allons compléter les lignes vides avec la donnée de 2013 si cela est possible.
Pour les deux pays "Germany" et "Russia" qui n'ont pas de données : nous cherchons une autre source de données car à ce stade il est difficile de les exclure de l'étude.

In [1094]:
years_to_keep = ['2014', '2013'] 
# taux remplissage 13/15 pour 2013 et 7/15 pour 2014.

# Nous avons vérifier que les données de 2016 ne présentent pas d'aberrances en comparaison avec les autres années.
df_1.drop(columns = ['2010', '2011', '2012', '2015', '2016','2020', '2025', '2030'], inplace=True)
#display(df_1)

# Imputation des valeurs manquantes de 2014 à partir de 2013
# On remplace les NaN par des 0
df_1.fillna(0, inplace=True)
#display(df_1)

df_11 = df_1.copy()
for index, row in df_1.iterrows():
    nb_2013, nb_2014 = row[2], row[3]
    #print("a", row["Country Name"], row[3], row[4], end="\n\n")
    if nb_2014 == float(0): # on avait un NaN
        df_11.at[index, '2014'] = nb_2013 # df.at[index, nom colonne à changer] = nouvelle valeur
        #print("b", row["Country Name"], row[3], row[4], end="\n\n\n\n")

# tri dans l'ordre décroissant
df_11.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_11)


Country Name  \
131948               Japan   
260223      United Kingdom   
135613         Korea, Rep.   
87968               France   
128283               Italy   
190588              Poland   
40323               Canada   
51318                Chile   
230903               Spain   
263888       United States   
11003            Australia   
212578        Saudi Arabia   
168598         Netherlands   
95298              Germany   
205248  Russian Federation   

                                                      Indicator Name  \
131948  Adjusted net enrolment rate, upper secondary, both sexes (%)   
260223  Adjusted net enrolment rate, upper secondary, both sexes (%)   
135613  Adjusted net enrolment rate, upper secondary, both sexes (%)   
87968   Adjusted net enrolment rate, upper secondary, both sexes (%)   
128283  Adjusted net enrolment rate, upper secondary, both sexes (%)   
190588  Adjusted net enrolment rate, upper secondary, both sexes (%)   
40323   Adjusted net enrolment rate, upper secondary, both sexes (%)   
51318   Adjusted net enrolment rate, upper secondary, both sexes (%)   
230903  Adjusted net enrolment rate, upper secondary, both sexes (%)   
263888  Adjusted net enrolment rate, upper secondary, both sexes (%)   
11003   Adjusted net enrolment rate, upper secondary, both sexes (%)   
212578  Adjusted net enrolment rate, upper secondary, both sexes (%)   
168598  Adjusted net enrolment rate, upper secondary, both sexes (%)   
95298   Adjusted net enrolment rate, upper secondary, both sexes (%)   
205248  Adjusted net enrolment rate, upper secondary, both sexes (%)   

             2013       2014  
131948  97.071823  97.071823  
260223  88.727089  92.257690  
135613  91.108917  91.108917  
87968   87.904182  88.872711  
128283  88.781151  88.781151  
190588  85.990601  85.990601  
40323   84.529091  84.529091  
51318   82.885231  82.265427  
230903  78.541397  80.409363  
263888  77.483688  79.888199  
11003   76.045959  76.045959  
212578  61.348930  69.297653  
168598  56.670990  56.299019  
95298    0.000000   0.000000  
205248   0.000000   0.000000

## 2 : 'Net enrolment rate, upper secondary, both sexes (%)'

In [1095]:
ind_att = attendance_ind[1]
df_2 = df_final.copy()
df_2 = df_2[df_2["Indicator Name"] == ind_att]
#display(df_2)

In [1096]:
years_to_keep = ['2014', '2013']
# taux remplissage 13/15 pour 2013 et 7/15 pour 2014

df_2.drop(columns = ['2010', '2011', '2012', '2015', '2016','2020', '2025', '2030'], inplace=True)
#display(df_2)

df_2.fillna(0, inplace=True)
#display(df_2)

df_22 = df_2.copy()
for index, row in df_2.iterrows():
    nb_2013, nb_2014 = row[2], row[3]
    if nb_2014 == float(0): # on avait un NaN
        df_22.at[index, '2014'] = nb_2013 # df.at[index, nom colonne à changer] = nouvelle valeur

# tri dans l'ordre décroissant
df_22.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_22)

Country Name  \
133598               Japan   
261873      United Kingdom   
137263         Korea, Rep.   
129933               Italy   
89618               France   
192238              Poland   
41973               Canada   
52968                Chile   
232553               Spain   
265538       United States   
12653            Australia   
214228        Saudi Arabia   
170248         Netherlands   
96948              Germany   
206898  Russian Federation   

                                             Indicator Name       2013  \
133598  Net enrolment rate, upper secondary, both sexes (%)  97.071823   
261873  Net enrolment rate, upper secondary, both sexes (%)  88.055313   
137263  Net enrolment rate, upper secondary, both sexes (%)  90.764183   
129933  Net enrolment rate, upper secondary, both sexes (%)  88.488457   
89618   Net enrolment rate, upper secondary, both sexes (%)  86.942642   
192238  Net enrolment rate, upper secondary, both sexes (%)  85.833992   
41973   Net enrolment rate, upper secondary, both sexes (%)  84.529091   
52968   Net enrolment rate, upper secondary, both sexes (%)  82.831802   
232553  Net enrolment rate, upper secondary, both sexes (%)  78.532738   
265538  Net enrolment rate, upper secondary, both sexes (%)  76.976212   
12653   Net enrolment rate, upper secondary, both sexes (%)  72.538437   
214228  Net enrolment rate, upper secondary, both sexes (%)  61.339520   
170248  Net enrolment rate, upper secondary, both sexes (%)  54.423538   
96948   Net enrolment rate, upper secondary, both sexes (%)   0.000000   
206898  Net enrolment rate, upper secondary, both sexes (%)   0.000000   

             2014  
133598  97.071823  
261873  91.964752  
137263  90.764183  
129933  88.488457  
89618   87.876183  
192238  85.833992  
41973   84.529091  
52968   82.213783  
232553  80.398109  
265538  79.378113  
12653   72.538437  
214228  69.288483  
170248  53.866928  
96948    0.000000  
206898   0.000000

## 3 : 'Enrolment in tertiary education per 100,000 inhabitants, both sexes'

In [1097]:
ind_att = attendance_ind[2]
df_3 = df_final.copy()
df_3 = df_3[df_3["Indicator Name"] == ind_att]
#display(df_3)

In [1098]:
# on ne garde pas les autres années : avec 2014 on peut compléter 2015 et pour le Japon on complétera 2015 avec 2013  
years_to_keep = ['2015', '2014', '2013'] 

df_3.drop(columns = ['2010', '2011', '2012', '2016','2020', '2025', '2030'], inplace=True)
#display(df_3)

df_3.fillna(0, inplace=True)
#display(df_3)

df_33 = df_3.copy()
for index, row in df_3.iterrows():
    nb_2013, nb_2014, nb_2015 = row[2], row[3], row[4]
    if nb_2015 == float(0):
        if nb_2014 != float(0): # on avait un NaN
            df_33.at[index, '2015'] = nb_2014 # df.at[index, nom colonne à changer] = nouvelle valeur
        elif nb_2013 != float(0):
            df_33.at[index, '2015'] = nb_2013

df_33.sort_values(by=years_to_keep, ascending=False, inplace=True) 
df_33.drop(columns = ['2013', '2014'], inplace=True) # apres la comparaison on retire les anciennes années

display(df_33)

Country Name  \
52511                Chile   
136806         Korea, Rep.   
265081       United States   
12196            Australia   
191781              Poland   
206441  Russian Federation   
213771        Saudi Arabia   
232096               Spain   
89161               France   
261416      United Kingdom   
96491              Germany   
129476               Italy   
133141               Japan   
41516               Canada   
169791         Netherlands   

                                                             Indicator Name  \
52511   Enrolment in tertiary education per 100,000 inhabitants, both sexes   
136806  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
265081  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
12196   Enrolment in tertiary education per 100,000 inhabitants, both sexes   
191781  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
206441  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
213771  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
232096  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
89161   Enrolment in tertiary education per 100,000 inhabitants, both sexes   
261416  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
96491   Enrolment in tertiary education per 100,000 inhabitants, both sexes   
129476  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
133141  Enrolment in tertiary education per 100,000 inhabitants, both sexes   
41516   Enrolment in tertiary education per 100,000 inhabitants, both sexes   
169791  Enrolment in tertiary education per 100,000 inhabitants, both sexes   

               2015  
52511   6784.923340  
136806  6705.078125  
265081  6166.944824  
12196   6153.159180  
191781  4926.934570  
206441  4877.473145  
213771  4845.896484  
232096  4284.855469  
89161   3725.566895  
261416  3657.521240  
96491   3611.083008  
129476  3133.108154  
133141  3041.894775  
41516      0.000000  
169791     0.000000

## 4 : 'Enrolment in tertiary education, all programmes, both sexes (number)'

In [1099]:
ind_att = attendance_ind[3]
df_4 = df_final.copy()
df_4 = df_4[df_4["Indicator Name"] == ind_att]
#display(df_4)

In [1100]:
# on ne garde pas les autres années : avec 2014 on peut compléter 2015 et pour le Japon on complétera 2015 avec 2013  
years_to_keep = ['2015', '2014', '2013'] 

df_4.drop(columns = ['2010', '2011', '2012', '2016', '2020', '2025', '2030'], inplace=True)
#display(df_4)

df_4.fillna(0, inplace=True)
#display(df_4)

df_44 = df_4.copy()
for index, row in df_4.iterrows():
    nb_2013, nb_2014, nb_2015 = row[2], row[3], row[4]
    if nb_2015 == float(0):
        if nb_2014 != float(0): # on avait un NaN
            df_44.at[index, '2015'] = nb_2014 # df.at[index, nom colonne à changer] = nouvelle valeur
        elif nb_2013 != float(0):
            df_44.at[index, '2015'] = nb_2013

df_44.sort_values(by=years_to_keep, ascending=False, inplace=True) 
df_44.drop(columns=['2013', '2014'], inplace=True) # apres la comparaison on retire les anciennes années

display(df_44)
df_44.to_csv("csv/nb_inscrits_superieur.csv", index=False)

Country Name  \
265084       United States   
206444  Russian Federation   
133144               Japan   
136809         Korea, Rep.   
96494              Germany   
89164               France   
261419      United Kingdom   
232099               Spain   
129479               Italy   
191784              Poland   
213774        Saudi Arabia   
12199            Australia   
52514                Chile   
169794         Netherlands   
41519               Canada   

                                                              Indicator Name  \
265084  Enrolment in tertiary education, all programmes, both sexes (number)   
206444  Enrolment in tertiary education, all programmes, both sexes (number)   
133144  Enrolment in tertiary education, all programmes, both sexes (number)   
136809  Enrolment in tertiary education, all programmes, both sexes (number)   
96494   Enrolment in tertiary education, all programmes, both sexes (number)   
89164   Enrolment in tertiary education, all programmes, both sexes (number)   
261419  Enrolment in tertiary education, all programmes, both sexes (number)   
232099  Enrolment in tertiary education, all programmes, both sexes (number)   
129479  Enrolment in tertiary education, all programmes, both sexes (number)   
191784  Enrolment in tertiary education, all programmes, both sexes (number)   
213774  Enrolment in tertiary education, all programmes, both sexes (number)   
12199   Enrolment in tertiary education, all programmes, both sexes (number)   
52514   Enrolment in tertiary education, all programmes, both sexes (number)   
169794  Enrolment in tertiary education, all programmes, both sexes (number)   
41519   Enrolment in tertiary education, all programmes, both sexes (number)   

               2015  
265084  19531728.00  
206444   6592416.00  
133144   3862460.00  
136809   3268099.00  
96494    2977781.00  
89164    2388880.00  
261419   2352932.75  
232099   1963924.00  
129479   1826477.00  
191784   1762666.00  
213774   1527769.00  
12199    1453521.00  
52514    1221774.00  
169794    842601.00  
41519          0.00

## 5 : 'Enrolment in upper secondary education, both sexes (number)'

In [1101]:
ind_att = attendance_ind[4]
df_5 = df_final.copy()
df_5 = df_5[df_5["Indicator Name"] == ind_att]
#display(df_5)

In [1102]:
years_to_keep = ['2014', '2013']
# taux remplissage 13/15 pour 2013 et 7/15 pour 2014

df_5.drop(columns = ['2010', '2011', '2012', '2015', '2016','2020', '2025', '2030'], inplace=True)
#display(df_5)

df_5.fillna(0, inplace=True)
#display(df_5)

df_55 = df_5.copy()
for index, row in df_5.iterrows():
    nb_2013, nb_2014 = row[2], row[3]
    if nb_2014 == float(0): # on avait un NaN
        df_55.at[index, '2014'] = nb_2013 # df.at[index, nom colonne à changer] = nouvelle valeur

df_55.sort_values(by=years_to_keep, ascending=False, inplace=True) 
df_55.drop(columns='2013', inplace=True) # apres la comparaison on retire les anciennes années

display(df_55)
df_55.to_csv("csv/nb_inscrits_secondaire.csv", index=False)

Country Name  \
265094       United States   
261429      United Kingdom   
133154               Japan   
206454  Russian Federation   
129489               Italy   
89174               France   
96504              Germany   
136819         Korea, Rep.   
213784        Saudi Arabia   
232109               Spain   
191794              Poland   
41529               Canada   
12209            Australia   
52524                Chile   
169804         Netherlands   

                                                     Indicator Name  \
265094  Enrolment in upper secondary education, both sexes (number)   
261429  Enrolment in upper secondary education, both sexes (number)   
133154  Enrolment in upper secondary education, both sexes (number)   
206454  Enrolment in upper secondary education, both sexes (number)   
129489  Enrolment in upper secondary education, both sexes (number)   
89174   Enrolment in upper secondary education, both sexes (number)   
96504   Enrolment in upper secondary education, both sexes (number)   
136819  Enrolment in upper secondary education, both sexes (number)   
213784  Enrolment in upper secondary education, both sexes (number)   
232109  Enrolment in upper secondary education, both sexes (number)   
191794  Enrolment in upper secondary education, both sexes (number)   
41529   Enrolment in upper secondary education, both sexes (number)   
12209   Enrolment in upper secondary education, both sexes (number)   
52524   Enrolment in upper secondary education, both sexes (number)   
169804  Enrolment in upper secondary education, both sexes (number)   

               2014  
265094  11736315.00  
261429   4195081.50  
133154   3682920.00  
206454   2823004.00  
129489   2780440.00  
89174    2598357.00  
96504    2579952.25  
136819   1903857.00  
213784   1678613.00  
232109   1662580.00  
191794   1589524.00  
41529    1531393.00  
12209    1104162.00  
52524    1032041.00  
169804    746415.00

## 6 : 'Gross enrolment ratio, tertiary, both sexes (%)'

In [1103]:
ind_att = attendance_ind[5]
df_6 = df_final.copy()
df_6 = df_6[df_6["Indicator Name"] == ind_att]
#display(df_6)

In [1104]:
years_to_keep = ['2015', '2014']
# taux remplissage 13/15 pour 2013 et 7/15 pour 2014

df_6.drop(columns = ['2010', '2011', '2012', '2013', '2016','2020', '2025', '2030'], inplace=True)
#display(df_6)

# Imputation des valeurs manquantes de 2014 à partir de 2013
# On remplace les NaN par des 0
df_6.fillna(0, inplace=True)
#display(df_6)

df_66 = df_6.copy()
for index, row in df_6.iterrows():
    nb_2014, nb_2015 = row[2], row[3]
    if row[0] == 'Netherlands': # exception !! car pas de valeur pour 2015 et 2014
        df_66.at[index, '2015'] = 78.501068 # on choisit la cellule 2012
    elif nb_2015 == float(0) and nb_2014 != float(0): # on avait un NaN
        df_66.at[index, '2015'] = nb_2014 # df.at[index, nom colonne à changer] = nouvelle valeur

# tri dans l'ordre décroissant
df_66.sort_values(by=years_to_keep, ascending=False, inplace=True) 
df_66.drop(columns = '2014', inplace=True) # apres la comparaison on retire les anciennes années

display(df_66)
df_66.to_csv("csv/poursuite_etudes_sup.csv", index=False)

Country Name                                   Indicator Name  \
136944         Korea, Rep.  Gross enrolment ratio, tertiary, both sexes (%)   
12334            Australia  Gross enrolment ratio, tertiary, both sexes (%)   
232234               Spain  Gross enrolment ratio, tertiary, both sexes (%)   
52649                Chile  Gross enrolment ratio, tertiary, both sexes (%)   
265219       United States  Gross enrolment ratio, tertiary, both sexes (%)   
206579  Russian Federation  Gross enrolment ratio, tertiary, both sexes (%)   
169929         Netherlands  Gross enrolment ratio, tertiary, both sexes (%)   
96629              Germany  Gross enrolment ratio, tertiary, both sexes (%)   
191919              Poland  Gross enrolment ratio, tertiary, both sexes (%)   
89299               France  Gross enrolment ratio, tertiary, both sexes (%)   
133279               Japan  Gross enrolment ratio, tertiary, both sexes (%)   
213909        Saudi Arabia  Gross enrolment ratio, tertiary, both sexes (%)   
129614               Italy  Gross enrolment ratio, tertiary, both sexes (%)   
261554      United Kingdom  Gross enrolment ratio, tertiary, both sexes (%)   
41654               Canada  Gross enrolment ratio, tertiary, both sexes (%)   

             2015  
136944  93.179138  
12334   90.306503  
232234  89.670143  
52649   88.577293  
265219  85.795776  
206579  80.394081  
169929  78.501068  
96629   68.265587  
191919  68.113617  
89299   64.390472  
133279  63.362591  
213909  63.066219  
129614  62.496071  
261554  56.476768  
41654    0.000000

## 7 : 'Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)'

In [1105]:
ind_att = attendance_ind[6]
df_7 = df_final.copy()
df_7 = df_7[df_7["Indicator Name"] == ind_att]
#display(df_7)

In [1106]:
 # on ne garde pas les autres années : avec 2014 on peut compléter 2015 et pour le Japon on complétera 2015 avec 2013 
years_to_keep = ['2015', '2014', '2013']

df_7.drop(columns = ['2010', '2011', '2012', '2016','2020', '2025', '2030'], inplace=True)
#display(df_7)

df_7.fillna(0, inplace=True)
#display(df_7)

df_77 = df_7.copy()
for index, row in df_7.iterrows():
    nb_2013, nb_2014, nb_2015 = row[2], row[3], row[4]
    if row[0] == 'Netherlands': # exception !! car pas de valeur pour 2015 et 2014
        df_77.at[index, '2015'] = 2.001320 # on choisit la cellule 2012
    if nb_2015 == float(0):
        if nb_2014 != float(0): # on avait un NaN
            df_77.at[index, '2015'] = nb_2014 # df.at[index, nom colonne à changer] = nouvelle valeur
        elif nb_2013 != float(0):
            df_77.at[index, '2015'] = nb_2013

# tri dans l'ordre décroissant
df_77.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_77)

Country Name  \
265726       United States   
53156                Chile   
137451         Korea, Rep.   
89806               France   
133786               Japan   
232741               Spain   
207086  Russian Federation   
12841            Australia   
262061      United Kingdom   
214416        Saudi Arabia   
170436         Netherlands   
192426              Poland   
130121               Italy   
97136              Germany   
42161               Canada   

                                                                              Indicator Name  \
265726  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
53156   Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
137451  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
89806   Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
133786  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
232741  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
207086  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
12841   Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
262061  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
214416  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
170436  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
192426  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
130121  Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
97136   Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   
42161   Percentage of all students in tertiary education enrolled in ISCED 5, both sexes (%)   

             2013       2014       2015  
265726  37.199070  37.234058  37.234058  
53156   27.749060  28.807360  28.807360  
137451  23.499041   0.000000  23.499041  
89806   21.593960  21.085661  21.085661  
133786  19.821609   0.000000  19.821609  
232741  17.588079  18.467159  18.467159  
207086  17.307911  17.331810  17.331810  
12841   16.162790  16.045040  16.045040  
262061  13.696640  12.127110  12.127110  
214416  11.286950  10.255160  10.255160  
170436   0.000000   0.000000   2.001320  
192426   0.573230   0.000000   0.573230  
130121   0.132750   0.000000   0.132750  
97136    0.019420   0.016340   0.016340  
42161    0.000000   0.000000   0.000000

Remarque : les données ci-dessus pour l'Allemagne et l'Italie sont peut-être abberantes.

## 8 : 'Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)'


In [1107]:
ind_att = attendance_ind[7]
df_8 = df_final.copy()
df_8 = df_8[df_8["Indicator Name"] == ind_att]
#display(df_8)

In [1108]:
years_to_keep = ['2014', '2013']
# taux remplissage 13/15 pour 2013 et 7/15 pour 2014

df_8.drop(columns = ['2010', '2011', '2012', '2015', '2016','2020', '2025', '2030'], inplace=True)
#display(df_8)

# Imputation des valeurs manquantes de 2014 à partir de 2013
# On remplace les NaN par des 0
df_8.fillna(0, inplace=True)
#display(df_8)

df_88 = df_8.copy()
for index, row in df_8.iterrows():
    nb_2013, nb_2014 = row[2], row[3]
    if nb_2014 == float(0): # on avait un NaN
        df_88.at[index, '2014'] = nb_2013 # df.at[index, nom colonne à changer] = nouvelle valeur

df_88.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_88)

Country Name  \
214417        Saudi Arabia   
133787               Japan   
137452         Korea, Rep.   
192427              Poland   
262062      United Kingdom   
12842            Australia   
53157                Chile   
97137              Germany   
232742               Spain   
130122               Italy   
265727       United States   
207087  Russian Federation   
89807               France   
42162               Canada   
170437         Netherlands   

                                                                              Indicator Name  \
214417  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
133787  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
137452  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
192427  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
262062  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
12842   Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
53157   Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
97137   Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
232742  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
130122  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
265727  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
207087  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
89807   Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
42162   Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   
170437  Percentage of all students in tertiary education enrolled in ISCED 6, both sexes (%)   

             2013       2014  
214417  83.425873  84.665909  
133787  69.482643  69.482643  
137452  66.752930  66.752930  
192427  66.561150  66.561150  
262062  63.981251  65.139000  
12842   65.151192  64.028999  
53157   64.352722  63.403961  
97137   58.845299  59.570930  
232742  55.093170  59.548359  
130122  59.180019  59.180019  
265727  48.227409  48.038830  
207087  30.145281  42.809059  
89807   39.850052  40.246769  
42162    0.000000   0.000000  
170437   0.000000   0.000000

## 9 : 'Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total'


In [1109]:
ind_att = attendance_ind[8]
df_9 = df_final.copy()
df_9 = df_9[df_9["Indicator Name"] == ind_att]
#display(df_9)

In [1110]:
years_to_keep = ['2030', '2025', '2020', '2015'] 

df_9.drop(columns = ['2010', '2011', '2012', '2013', '2014', '2016'], inplace=True)
#display(df_9)

# tri dans l'ordre décroissant, d'abord 2030 puis 2025 puis 2020.
df_9.sort_values(by=years_to_keep, ascending=False, inplace=True) 
df_9.drop(columns = '2015', inplace=True) # apres la comparaison on retire les anciennes années

display(df_9)
df_9.to_csv("csv/projection_jeunes_diplomes_secondaire.csv", index=False)

Country Name  \
43767               Canada   
139057         Korea, Rep.   
135392               Japan   
91412               France   
14447            Australia   
216022        Saudi Arabia   
263667      United Kingdom   
98742              Germany   
267332       United States   
234347               Spain   
172042         Netherlands   
194032              Poland   
54762                Chile   
208692  Russian Federation   
131727               Italy   

                                                                                                                           Indicator Name  \
43767   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
139057  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
135392  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
91412   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
14447   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
216022  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
263667  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
98742   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
267332  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
234347  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
172042  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
194032  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
54762   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
208692  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
131727  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   

        2020  2025  2030  
43767   0.64  0.66  0.68  
139057  0.61  0.66  0.68  
135392  0.61  0.65  0.67  
91412   0.43  0.46  0.49  
14447   0.43  0.45  0.47  
216022  0.38  0.42  0.45  
263667  0.38  0.41  0.43  
98742   0.38  0.40  0.42  
267332  0.38  0.40  0.41  
234347  0.35  0.38  0.41  
172042  0.34  0.37  0.39  
194032  0.28  0.30  0.31  
54762   0.24  0.26  0.28  
208692  0.24  0.24  0.25  
131727  0.18  0.20  0.22

## 10 : 'Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total


In [1111]:
ind_att = attendance_ind[9]
df_10 = df_final.copy()
df_10 = df_10[df_10["Indicator Name"] == ind_att]
#display(df_10)

In [1112]:
years_to_keep = ['2030', '2025', '2020', '2015'] 

df_10.drop(columns = ['2010', '2011', '2012', '2013', '2014', '2016'], inplace=True)
#display(df_10)

df_10.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_10)

Country Name  \
43893               Canada   
139183         Korea, Rep.   
135518               Japan   
14573            Australia   
267458       United States   
98868              Germany   
91538               France   
263793      United Kingdom   
172168         Netherlands   
216148        Saudi Arabia   
234473               Spain   
194158              Poland   
208818  Russian Federation   
54888                Chile   
131853               Italy   

                                                                                                                       Indicator Name  \
43893   Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
139183  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
135518  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
14573   Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
267458  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
98868   Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
91538   Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
263793  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
172168  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
216148  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
234473  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
194158  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
208818  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
54888   Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   
131853  Wittgenstein Projection: Percentage of the total population by highest level of educational attainment. Post Secondary. Total   

        2015  2020  2025  2030  
43893   0.44  0.47  0.48  0.50  
139183  0.31  0.35  0.39  0.43  
135518  0.32  0.35  0.39  0.42  
14573   0.26  0.28  0.30  0.32  
267458  0.27  0.28  0.30  0.31  
98868   0.26  0.28  0.29  0.31  
91538   0.21  0.23  0.26  0.29  
263793  0.22  0.24  0.25  0.27  
172168  0.22  0.23  0.25  0.27  
216148  0.18  0.21  0.24  0.27  
234473  0.18  0.20  0.22  0.24  
194158  0.17  0.18  0.20  0.21  
208818  0.17  0.17  0.18  0.19  
54888   0.12  0.13  0.15  0.16  
131853  0.10  0.11  0.12  0.14

## 11 : 'Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total'

In [1113]:
ind_att = attendance_ind[10]
df_11 = df_final.copy()
df_11 = df_11[df_11["Indicator Name"] == ind_att]
#display(df_11)

In [1114]:
years_to_keep = ['2030', '2025', '2020','2015'] 

df_11.drop(columns = ['2010', '2011', '2012', '2013', '2014', '2016'], inplace=True)
#display(df_11)

df_11.sort_values(by=years_to_keep, ascending=False, inplace=True) 

display(df_11)

Country Name  \
43803               Canada   
139093         Korea, Rep.   
135428               Japan   
216058        Saudi Arabia   
267368       United States   
14483            Australia   
98778              Germany   
91448               France   
263703      United Kingdom   
172078         Netherlands   
234383               Spain   
194068              Poland   
208728  Russian Federation   
54798                Chile   
131763               Italy   

                                                                                                                         Indicator Name  \
43803   Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
139093  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
135428  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
216058  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
267368  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
14483   Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
98778   Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
91448   Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
263703  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
172078  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
234383  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
194068  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
208728  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
54798   Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   
131763  Wittgenstein Projection: Percentage of the population age 25+ by highest level of educational attainment. Post Secondary. Total   

        2015  2020  2025  2030  
43803   0.57  0.60  0.62  0.64  
139093  0.40  0.45  0.49  0.53  
135428  0.39  0.42  0.46  0.50  
216058  0.31  0.35  0.39  0.43  
267368  0.38  0.39  0.41  0.42  
14483   0.35  0.38  0.40  0.42  
98778   0.32  0.34  0.37  0.39  
91448   0.28  0.31  0.34  0.37  
263703  0.29  0.31  0.33  0.35  
172078  0.28  0.30  0.32  0.34  
234383  0.22  0.24  0.27  0.30  
194068  0.22  0.24  0.25  0.27  
208728  0.22  0.23  0.24  0.25  
54798   0.17  0.18  0.20  0.22  
131763  0.13  0.14  0.15  0.17

Conclusion : 
1) choix de 4 indicateurs pertinents pour le niveau d'éducation de la population.

2) ajouter des scores au dictionnaire des scores.


Nous gardons 4 indicateurs :

- **Enrolment in tertiary education, all programmes, both sexes (number)** : df_44, "nb_inscrits_superieur.csv"

Nous donne le nombre d’étudiants inscrits dans l’enseignement supérieur, manque une donnée : Canada.

- **Enrolment in upper secondary education, both sexes (number)** : df_55, "nb_inscrits_secondaire.csv"
- **Gross enrolment ratio, tertiary, both sexes (%)** : df_66, "poursuite_etudes_sup.csv"

Nous donne le pourcentage d’étudiants poursuivant dans l’enseignement supérieur, manque une donnée : Canada.

- **Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total** : df_9, "projection_jeunes_diplomes_secondaire.csv"

Nous choisissons les indicateurs avec des nombres et non pas des pourcentages car nous ciblons les pays avec une grande population d’étudiants (enseignement supérieur, et enseignement secondaire car ce sont les étudiants de demain)

## Ajout des scores pour les 4 indicateurs d'éducation choisis

In [1115]:
df_isec = pd.read_csv("csv/nb_inscrits_secondaire.csv")
df_isup = pd.read_csv("csv/nb_inscrits_superieur.csv")
df_pour = pd.read_csv("csv/poursuite_etudes_sup.csv")
df_proj = pd.read_csv("csv/projection_jeunes_diplomes_secondaire.csv")

## 1) score inscrits secondaire

In [1116]:
# Ajout au score : pas de pb : taux de remplissage 100%
display(df_isec)

l_ins_second = df_isec["Country Name"].tolist()
add_score(score, l_ins_second)
print(score)

Country Name  \
0        United States   
1       United Kingdom   
2                Japan   
3   Russian Federation   
4                Italy   
5               France   
6              Germany   
7          Korea, Rep.   
8         Saudi Arabia   
9                Spain   
10              Poland   
11              Canada   
12           Australia   
13               Chile   
14         Netherlands   

                                                 Indicator Name         2014  
0   Enrolment in upper secondary education, both sexes (number)  11736315.00  
1   Enrolment in upper secondary education, both sexes (number)   4195081.50  
2   Enrolment in upper secondary education, both sexes (number)   3682920.00  
3   Enrolment in upper secondary education, both sexes (number)   2823004.00  
4   Enrolment in upper secondary education, both sexes (number)   2780440.00  
5   Enrolment in upper secondary education, both sexes (number)   2598357.00  
6   Enrolment in upper secondary education, both sexes (number)   2579952.25  
7   Enrolment in upper secondary education, both sexes (number)   1903857.00  
8   Enrolment in upper secondary education, both sexes (number)   1678613.00  
9   Enrolment in upper secondary education, both sexes (number)   1662580.00  
10  Enrolment in upper secondary education, both sexes (number)   1589524.00  
11  Enrolment in upper secondary education, both sexes (number)   1531393.00  
12  Enrolment in upper secondary education, both sexes (number)   1104162.00  
13  Enrolment in upper secondary education, both sexes (number)   1032041.00  
14  Enrolment in upper secondary education, both sexes (number)    746415.00

{'United States': 35, 'Russian Federation': 32, 'Japan': 39, 'Germany': 31, 'United Kingdom': 40, 'France': 28, 'Italy': 21, 'Korea, Rep.': 30, 'Spain': 20, 'Poland': 14, 'Canada': 20, 'Saudi Arabia': 15, 'Australia': 15, 'Chile': 6, 'Netherlands': 14}


## 2) score inscrits supérieur

In [1117]:
# ATTENTION CANADA : faire ajustement !
display(df_isup) 
df_isup_adj = df_isup.copy()

# CANADA
df_isup_adj.at[14, '2015'] = float(1575000) # voir support PowerPoint pour la source

df_isup_adj.sort_values(by='2015', ascending=False, inplace=True) 
display(df_isup_adj)

l_ins_sup = df_isup_adj["Country Name"].tolist()
add_score(score, l_ins_sup)
print(score)

df_isup_adj.to_csv("csv/nb_inscrits_superieur_adjusted.csv", index=False)

Country Name  \
0        United States   
1   Russian Federation   
2                Japan   
3          Korea, Rep.   
4              Germany   
5               France   
6       United Kingdom   
7                Spain   
8                Italy   
9               Poland   
10        Saudi Arabia   
11           Australia   
12               Chile   
13         Netherlands   
14              Canada   

                                                          Indicator Name  \
0   Enrolment in tertiary education, all programmes, both sexes (number)   
1   Enrolment in tertiary education, all programmes, both sexes (number)   
2   Enrolment in tertiary education, all programmes, both sexes (number)   
3   Enrolment in tertiary education, all programmes, both sexes (number)   
4   Enrolment in tertiary education, all programmes, both sexes (number)   
5   Enrolment in tertiary education, all programmes, both sexes (number)   
6   Enrolment in tertiary education, all programmes, both sexes (number)   
7   Enrolment in tertiary education, all programmes, both sexes (number)   
8   Enrolment in tertiary education, all programmes, both sexes (number)   
9   Enrolment in tertiary education, all programmes, both sexes (number)   
10  Enrolment in tertiary education, all programmes, both sexes (number)   
11  Enrolment in tertiary education, all programmes, both sexes (number)   
12  Enrolment in tertiary education, all programmes, both sexes (number)   
13  Enrolment in tertiary education, all programmes, both sexes (number)   
14  Enrolment in tertiary education, all programmes, both sexes (number)   

           2015  
0   19531728.00  
1    6592416.00  
2    3862460.00  
3    3268099.00  
4    2977781.00  
5    2388880.00  
6    2352932.75  
7    1963924.00  
8    1826477.00  
9    1762666.00  
10   1527769.00  
11   1453521.00  
12   1221774.00  
13    842601.00  
14         0.00

Country Name  \
0        United States   
1   Russian Federation   
2                Japan   
3          Korea, Rep.   
4              Germany   
5               France   
6       United Kingdom   
7                Spain   
8                Italy   
9               Poland   
14              Canada   
10        Saudi Arabia   
11           Australia   
12               Chile   
13         Netherlands   

                                                          Indicator Name  \
0   Enrolment in tertiary education, all programmes, both sexes (number)   
1   Enrolment in tertiary education, all programmes, both sexes (number)   
2   Enrolment in tertiary education, all programmes, both sexes (number)   
3   Enrolment in tertiary education, all programmes, both sexes (number)   
4   Enrolment in tertiary education, all programmes, both sexes (number)   
5   Enrolment in tertiary education, all programmes, both sexes (number)   
6   Enrolment in tertiary education, all programmes, both sexes (number)   
7   Enrolment in tertiary education, all programmes, both sexes (number)   
8   Enrolment in tertiary education, all programmes, both sexes (number)   
9   Enrolment in tertiary education, all programmes, both sexes (number)   
14  Enrolment in tertiary education, all programmes, both sexes (number)   
10  Enrolment in tertiary education, all programmes, both sexes (number)   
11  Enrolment in tertiary education, all programmes, both sexes (number)   
12  Enrolment in tertiary education, all programmes, both sexes (number)   
13  Enrolment in tertiary education, all programmes, both sexes (number)   

           2015  
0   19531728.00  
1    6592416.00  
2    3862460.00  
3    3268099.00  
4    2977781.00  
5    2388880.00  
6    2352932.75  
7    1963924.00  
8    1826477.00  
9    1762666.00  
14   1575000.00  
10   1527769.00  
11   1453521.00  
12   1221774.00  
13    842601.00

{'United States': 50, 'Russian Federation': 46, 'Japan': 52, 'Germany': 42, 'United Kingdom': 49, 'France': 38, 'Italy': 28, 'Korea, Rep.': 42, 'Spain': 28, 'Poland': 20, 'Canada': 25, 'Saudi Arabia': 19, 'Australia': 18, 'Chile': 8, 'Netherlands': 15}


## 3) score poursuite d'études supérieures

In [1118]:
# ATTENTION CANADA : faire ajustement 
display(df_pour)
df_pour_adj = df_pour.copy()

# CANADA : https://tradingeconomics.com/canada/school-enrollment-tertiary-percent-gross-wb-data.html
df_pour_adj.at[14, '2015'] = float(65)
df_pour_adj.sort_values(by='2015', ascending=False, inplace=True) 
display(df_pour_adj)

l_poursuite_sup = df_pour_adj["Country Name"].tolist()
add_score(score, l_poursuite_sup)
print(score)

df_pour_adj.to_csv("csv/poursuite_etudes_sup_adjusted.csv", index=False)

Country Name                                   Indicator Name  \
0          Korea, Rep.  Gross enrolment ratio, tertiary, both sexes (%)   
1            Australia  Gross enrolment ratio, tertiary, both sexes (%)   
2                Spain  Gross enrolment ratio, tertiary, both sexes (%)   
3                Chile  Gross enrolment ratio, tertiary, both sexes (%)   
4        United States  Gross enrolment ratio, tertiary, both sexes (%)   
5   Russian Federation  Gross enrolment ratio, tertiary, both sexes (%)   
6          Netherlands  Gross enrolment ratio, tertiary, both sexes (%)   
7              Germany  Gross enrolment ratio, tertiary, both sexes (%)   
8               Poland  Gross enrolment ratio, tertiary, both sexes (%)   
9               France  Gross enrolment ratio, tertiary, both sexes (%)   
10               Japan  Gross enrolment ratio, tertiary, both sexes (%)   
11        Saudi Arabia  Gross enrolment ratio, tertiary, both sexes (%)   
12               Italy  Gross enrolment ratio, tertiary, both sexes (%)   
13      United Kingdom  Gross enrolment ratio, tertiary, both sexes (%)   
14              Canada  Gross enrolment ratio, tertiary, both sexes (%)   

         2015  
0   93.179138  
1   90.306503  
2   89.670143  
3   88.577293  
4   85.795776  
5   80.394081  
6   78.501068  
7   68.265587  
8   68.113617  
9   64.390472  
10  63.362591  
11  63.066219  
12  62.496071  
13  56.476768  
14   0.000000

Country Name                                   Indicator Name  \
0          Korea, Rep.  Gross enrolment ratio, tertiary, both sexes (%)   
1            Australia  Gross enrolment ratio, tertiary, both sexes (%)   
2                Spain  Gross enrolment ratio, tertiary, both sexes (%)   
3                Chile  Gross enrolment ratio, tertiary, both sexes (%)   
4        United States  Gross enrolment ratio, tertiary, both sexes (%)   
5   Russian Federation  Gross enrolment ratio, tertiary, both sexes (%)   
6          Netherlands  Gross enrolment ratio, tertiary, both sexes (%)   
7              Germany  Gross enrolment ratio, tertiary, both sexes (%)   
8               Poland  Gross enrolment ratio, tertiary, both sexes (%)   
14              Canada  Gross enrolment ratio, tertiary, both sexes (%)   
9               France  Gross enrolment ratio, tertiary, both sexes (%)   
10               Japan  Gross enrolment ratio, tertiary, both sexes (%)   
11        Saudi Arabia  Gross enrolment ratio, tertiary, both sexes (%)   
12               Italy  Gross enrolment ratio, tertiary, both sexes (%)   
13      United Kingdom  Gross enrolment ratio, tertiary, both sexes (%)   

         2015  
0   93.179138  
1   90.306503  
2   89.670143  
3   88.577293  
4   85.795776  
5   80.394081  
6   78.501068  
7   68.265587  
8   68.113617  
14  65.000000  
9   64.390472  
10  63.362591  
11  63.066219  
12  62.496071  
13  56.476768

{'United States': 61, 'Russian Federation': 56, 'Japan': 56, 'Germany': 50, 'United Kingdom': 50, 'France': 43, 'Italy': 30, 'Korea, Rep.': 57, 'Spain': 41, 'Poland': 27, 'Canada': 31, 'Saudi Arabia': 22, 'Australia': 32, 'Chile': 20, 'Netherlands': 24}


## 4) score projection pourcentage de diplômés études supérieures

In [1119]:
display(df_proj)

l_proj = df_proj["Country Name"].tolist()
add_score(score, l_proj)
print(score)

Country Name  \
0               Canada   
1          Korea, Rep.   
2                Japan   
3               France   
4            Australia   
5         Saudi Arabia   
6       United Kingdom   
7              Germany   
8        United States   
9                Spain   
10         Netherlands   
11              Poland   
12               Chile   
13  Russian Federation   
14               Italy   

                                                                                                                       Indicator Name  \
0   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
1   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
2   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
3   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
4   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
5   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
6   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
7   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
8   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
9   Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
10  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
11  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
12  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
13  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   
14  Wittgenstein Projection: Percentage of the population age 20-39 by highest level of educational attainment. Post Secondary. Total   

    2020  2025  2030  
0   0.64  0.66  0.68  
1   0.61  0.66  0.68  
2   0.61  0.65  0.67  
3   0.43  0.46  0.49  
4   0.43  0.45  0.47  
5   0.38  0.42  0.45  
6   0.38  0.41  0.43  
7   0.38  0.40  0.42  
8   0.38  0.40  0.41  
9   0.35  0.38  0.41  
10  0.34  0.37  0.39  
11  0.28  0.30  0.31  
12  0.24  0.26  0.28  
13  0.24  0.24  0.25  
14  0.18  0.20  0.22

{'United States': 68, 'Russian Federation': 58, 'Japan': 69, 'Germany': 58, 'United Kingdom': 59, 'France': 55, 'Italy': 31, 'Korea, Rep.': 71, 'Spain': 47, 'Poland': 31, 'Canada': 46, 'Saudi Arabia': 32, 'Australia': 43, 'Chile': 23, 'Netherlands': 29}


**Nous avons mis des scores pour 6 indicateurs : un pour la population, un pour internet, 4 pour l'éducation**

**La note est sur 90 par pays.**

In [1120]:
#print(score) # notre dictionnaire des scores est à jour
dict(sorted(score.items(), key=lambda item: item[1], reverse=True)) # {k: v for k, v in sorted(score.items(), key=lambda item: item[1])}

{'Korea, Rep.': 71,
 'Japan': 69,
 'United States': 68,
 'United Kingdom': 59,
 'Russian Federation': 58,
 'Germany': 58,
 'France': 55,
 'Spain': 47,
 'Canada': 46,
 'Australia': 43,
 'Saudi Arabia': 32,
 'Italy': 31,
 'Poland': 31,
 'Netherlands': 29,
 'Chile': 23}

**On retire ces 8 pays dont le score est inférieur à 55 (France comme référence).**

- Espagne : 47
- Canada : 46 
- Australie : 43
- Arabie Saoudite : 32
- Italie : 31
- Pologne : 31
- Pays-Bas : 29 
- Chili : 23

**On garde donc 7 pays finaux** :

- Corée du Sud : 71
- Japon : 69
- Etats-Unis : 68
- Royaume-Uni : 59
- Allemagne et Russie : 58
- France : 55

In [1121]:
COUNTRIES_CHOSEN = ['Korea, Rep.', 'Japan', 'United States', 'United Kingdom', 'Germany', 'Russian Federation', 'France']

df_population_f = df_population.copy()
df_population_f = df_population_f[df_population_f['Country Name'].isin(COUNTRIES_CHOSEN) ] # on ne garde que les 7 pays choisis
df_population_f.to_csv("csv/population_final.csv", index=False)

df_internet_f = df_internet.copy()
df_internet_f = df_internet_f[df_internet_f['Country Name'].isin(COUNTRIES_CHOSEN) ] # on ne garde que les 7 pays choisis
df_internet_f.to_csv("csv/internet_final.csv", index=False)

df_isec_f = df_isec.copy()
df_isec_f = df_isec_f[df_isec_f['Country Name'].isin(COUNTRIES_CHOSEN) ]
df_isec_f.to_csv("csv/nb_inscrits_secondaire_final.csv", index=False)

df_isup_f = df_isup.copy()
df_isup_f = df_isup_f[df_isup_f['Country Name'].isin(COUNTRIES_CHOSEN) ] 
df_isup_f.to_csv("csv/nb_inscrits_superieur_final.csv", index=False)

df_isup_adj_f = df_isup_adj.copy()
df_isup_adj_f = df_isup_adj_f[df_isup_adj_f['Country Name'].isin(COUNTRIES_CHOSEN) ]
df_isup_adj_f.to_csv("csv/nb_inscrits_superieur_adjusted_final.csv", index=False)

df_pour_f = df_pour.copy()
df_pour_f = df_pour_f[df_pour_f['Country Name'].isin(COUNTRIES_CHOSEN) ] 
df_pour_f.to_csv("csv/poursuite_etudes_sup_final.csv", index=False)

df_pour_adj_f = df_pour_adj.copy()
df_pour_adj_f = df_pour_adj_f[df_pour_adj_f['Country Name'].isin(COUNTRIES_CHOSEN) ] 
df_pour_adj_f.to_csv("csv/poursuite_etudes_sup_adjusted_final.csv", index=False)

df_proj_f = df_proj.copy()
df_proj_f = df_proj_f[df_proj_f['Country Name'].isin(COUNTRIES_CHOSEN) ] 
df_proj_f.to_csv("csv/projection_jeunes_diplomes_secondaire_final.csv", index=False)

In [1122]:
# Affichage des 6 dataframes finaux par indicateur pertinent choisi.

#display(df_population_f)
#display(df_internet_f)
#display(df_isec_f)
#display(df_isup_f)
#display(df_isup_adj_f)
#display(df_pour_f)
#display(df_pour_adj_f)
#display(df_proj_f)